/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * event
 * @export
 * @interface CharactersCharacterIdCalendarGetInner
 */
export interface CharactersCharacterIdCalendarGetInner {
    /**
     * 
     * @type {Date}
     * @memberof CharactersCharacterIdCalendarGetInner
     */
    eventDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof CharactersCharacterIdCalendarGetInner
     */
    eventId?: number;
    /**
     * 
     * @type {string}
     * @memberof CharactersCharacterIdCalendarGetInner
     */
    eventResponse?: CharactersCharacterIdCalendarGetInnerEventResponseEnum;
    /**
     * 
     * @type {number}
     * @memberof CharactersCharacterIdCalendarGetInner
     */
    importance?: number;
    /**
     * 
     * @type {string}
     * @memberof CharactersCharacterIdCalendarGetInner
     */
    title?: string;
}


/**
 * @export
 */
export const CharactersCharacterIdCalendarGetInnerEventResponseEnum = {
    Declined: 'declined',
    NotResponded: 'not_responded',
    Accepted: 'accepted',
    Tentative: 'tentative'
} as const;
export type CharactersCharacterIdCalendarGetInnerEventResponseEnum = typeof CharactersCharacterIdCalendarGetInnerEventResponseEnum[keyof typeof CharactersCharacterIdCalendarGetInnerEventResponseEnum];


/**
 * Check if a given object implements the CharactersCharacterIdCalendarGetInner interface.
 */
export function instanceOfCharactersCharacterIdCalendarGetInner(value: object): value is CharactersCharacterIdCalendarGetInner {
    return true;
}

export function CharactersCharacterIdCalendarGetInnerFromJSON(json: any): CharactersCharacterIdCalendarGetInner {
    return CharactersCharacterIdCalendarGetInnerFromJSONTyped(json, false);
}

export function CharactersCharacterIdCalendarGetInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CharactersCharacterIdCalendarGetInner {
    if (json == null) {
        return json;
    }
    return {
        
        'eventDate': json['event_date'] == null ? undefined : (new Date(json['event_date'])),
        'eventId': json['event_id'] == null ? undefined : json['event_id'],
        'eventResponse': json['event_response'] == null ? undefined : json['event_response'],
        'importance': json['importance'] == null ? undefined : json['importance'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function CharactersCharacterIdCalendarGetInnerToJSON(json: any): CharactersCharacterIdCalendarGetInner {
    return CharactersCharacterIdCalendarGetInnerToJSONTyped(json, false);
}

export function CharactersCharacterIdCalendarGetInnerToJSONTyped(value?: CharactersCharacterIdCalendarGetInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event_date': value['eventDate'] == null ? undefined : ((value['eventDate']).toISOString()),
        'event_id': value['eventId'],
        'event_response': value['eventResponse'],
        'importance': value['importance'],
        'title': value['title'],
    };
}

