/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Full details of a specific event
 * @export
 * @interface CharactersCharacterIdCalendarEventIdGet
 */
export interface CharactersCharacterIdCalendarEventIdGet {
    /**
     * 
     * @type {Date}
     * @memberof CharactersCharacterIdCalendarEventIdGet
     */
    date: Date;
    /**
     * Length in minutes
     * @type {number}
     * @memberof CharactersCharacterIdCalendarEventIdGet
     */
    duration: number;
    /**
     * 
     * @type {number}
     * @memberof CharactersCharacterIdCalendarEventIdGet
     */
    eventId: number;
    /**
     * 
     * @type {number}
     * @memberof CharactersCharacterIdCalendarEventIdGet
     */
    importance: number;
    /**
     * 
     * @type {number}
     * @memberof CharactersCharacterIdCalendarEventIdGet
     */
    ownerId: number;
    /**
     * 
     * @type {string}
     * @memberof CharactersCharacterIdCalendarEventIdGet
     */
    ownerName: string;
    /**
     * 
     * @type {string}
     * @memberof CharactersCharacterIdCalendarEventIdGet
     */
    ownerType: CharactersCharacterIdCalendarEventIdGetOwnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CharactersCharacterIdCalendarEventIdGet
     */
    response: string;
    /**
     * 
     * @type {string}
     * @memberof CharactersCharacterIdCalendarEventIdGet
     */
    text: string;
    /**
     * 
     * @type {string}
     * @memberof CharactersCharacterIdCalendarEventIdGet
     */
    title: string;
}


/**
 * @export
 */
export const CharactersCharacterIdCalendarEventIdGetOwnerTypeEnum = {
    EveServer: 'eve_server',
    Corporation: 'corporation',
    Faction: 'faction',
    Character: 'character',
    Alliance: 'alliance'
} as const;
export type CharactersCharacterIdCalendarEventIdGetOwnerTypeEnum = typeof CharactersCharacterIdCalendarEventIdGetOwnerTypeEnum[keyof typeof CharactersCharacterIdCalendarEventIdGetOwnerTypeEnum];


/**
 * Check if a given object implements the CharactersCharacterIdCalendarEventIdGet interface.
 */
export function instanceOfCharactersCharacterIdCalendarEventIdGet(value: object): value is CharactersCharacterIdCalendarEventIdGet {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('duration' in value) || value['duration'] === undefined) return false;
    if (!('eventId' in value) || value['eventId'] === undefined) return false;
    if (!('importance' in value) || value['importance'] === undefined) return false;
    if (!('ownerId' in value) || value['ownerId'] === undefined) return false;
    if (!('ownerName' in value) || value['ownerName'] === undefined) return false;
    if (!('ownerType' in value) || value['ownerType'] === undefined) return false;
    if (!('response' in value) || value['response'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function CharactersCharacterIdCalendarEventIdGetFromJSON(json: any): CharactersCharacterIdCalendarEventIdGet {
    return CharactersCharacterIdCalendarEventIdGetFromJSONTyped(json, false);
}

export function CharactersCharacterIdCalendarEventIdGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): CharactersCharacterIdCalendarEventIdGet {
    if (json == null) {
        return json;
    }
    return {
        
        'date': (new Date(json['date'])),
        'duration': json['duration'],
        'eventId': json['event_id'],
        'importance': json['importance'],
        'ownerId': json['owner_id'],
        'ownerName': json['owner_name'],
        'ownerType': json['owner_type'],
        'response': json['response'],
        'text': json['text'],
        'title': json['title'],
    };
}

export function CharactersCharacterIdCalendarEventIdGetToJSON(json: any): CharactersCharacterIdCalendarEventIdGet {
    return CharactersCharacterIdCalendarEventIdGetToJSONTyped(json, false);
}

export function CharactersCharacterIdCalendarEventIdGetToJSONTyped(value?: CharactersCharacterIdCalendarEventIdGet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': ((value['date']).toISOString()),
        'duration': value['duration'],
        'event_id': value['eventId'],
        'importance': value['importance'],
        'owner_id': value['ownerId'],
        'owner_name': value['ownerName'],
        'owner_type': value['ownerType'],
        'response': value['response'],
        'text': value['text'],
        'title': value['title'],
    };
}

