/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * content object
 * @export
 * @interface CharactersCharacterIdPlanetsPlanetIdGetPinsInnerContentsInner
 */
export interface CharactersCharacterIdPlanetsPlanetIdGetPinsInnerContentsInner {
    /**
     * 
     * @type {number}
     * @memberof CharactersCharacterIdPlanetsPlanetIdGetPinsInnerContentsInner
     */
    amount: number;
    /**
     * 
     * @type {number}
     * @memberof CharactersCharacterIdPlanetsPlanetIdGetPinsInnerContentsInner
     */
    typeId: number;
}

/**
 * Check if a given object implements the CharactersCharacterIdPlanetsPlanetIdGetPinsInnerContentsInner interface.
 */
export function instanceOfCharactersCharacterIdPlanetsPlanetIdGetPinsInnerContentsInner(value: object): value is CharactersCharacterIdPlanetsPlanetIdGetPinsInnerContentsInner {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('typeId' in value) || value['typeId'] === undefined) return false;
    return true;
}

export function CharactersCharacterIdPlanetsPlanetIdGetPinsInnerContentsInnerFromJSON(json: any): CharactersCharacterIdPlanetsPlanetIdGetPinsInnerContentsInner {
    return CharactersCharacterIdPlanetsPlanetIdGetPinsInnerContentsInnerFromJSONTyped(json, false);
}

export function CharactersCharacterIdPlanetsPlanetIdGetPinsInnerContentsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CharactersCharacterIdPlanetsPlanetIdGetPinsInnerContentsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'typeId': json['type_id'],
    };
}

export function CharactersCharacterIdPlanetsPlanetIdGetPinsInnerContentsInnerToJSON(json: any): CharactersCharacterIdPlanetsPlanetIdGetPinsInnerContentsInner {
    return CharactersCharacterIdPlanetsPlanetIdGetPinsInnerContentsInnerToJSONTyped(json, false);
}

export function CharactersCharacterIdPlanetsPlanetIdGetPinsInnerContentsInnerToJSONTyped(value?: CharactersCharacterIdPlanetsPlanetIdGetPinsInnerContentsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'type_id': value['typeId'],
    };
}

