/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CharactersCharacterIdMedalsGetInnerGraphicsInner } from './CharactersCharacterIdMedalsGetInnerGraphicsInner';
import {
    CharactersCharacterIdMedalsGetInnerGraphicsInnerFromJSON,
    CharactersCharacterIdMedalsGetInnerGraphicsInnerFromJSONTyped,
    CharactersCharacterIdMedalsGetInnerGraphicsInnerToJSON,
    CharactersCharacterIdMedalsGetInnerGraphicsInnerToJSONTyped,
} from './CharactersCharacterIdMedalsGetInnerGraphicsInner';

/**
 * 
 * @export
 * @interface CharactersCharacterIdMedalsGetInner
 */
export interface CharactersCharacterIdMedalsGetInner {
    /**
     * 
     * @type {number}
     * @memberof CharactersCharacterIdMedalsGetInner
     */
    corporationId: number;
    /**
     * 
     * @type {Date}
     * @memberof CharactersCharacterIdMedalsGetInner
     */
    date: Date;
    /**
     * 
     * @type {string}
     * @memberof CharactersCharacterIdMedalsGetInner
     */
    description: string;
    /**
     * 
     * @type {Array<CharactersCharacterIdMedalsGetInnerGraphicsInner>}
     * @memberof CharactersCharacterIdMedalsGetInner
     */
    graphics: Array<CharactersCharacterIdMedalsGetInnerGraphicsInner>;
    /**
     * 
     * @type {number}
     * @memberof CharactersCharacterIdMedalsGetInner
     */
    issuerId: number;
    /**
     * 
     * @type {number}
     * @memberof CharactersCharacterIdMedalsGetInner
     */
    medalId: number;
    /**
     * 
     * @type {string}
     * @memberof CharactersCharacterIdMedalsGetInner
     */
    reason: string;
    /**
     * 
     * @type {string}
     * @memberof CharactersCharacterIdMedalsGetInner
     */
    status: CharactersCharacterIdMedalsGetInnerStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof CharactersCharacterIdMedalsGetInner
     */
    title: string;
}


/**
 * @export
 */
export const CharactersCharacterIdMedalsGetInnerStatusEnum = {
    Public: 'public',
    Private: 'private'
} as const;
export type CharactersCharacterIdMedalsGetInnerStatusEnum = typeof CharactersCharacterIdMedalsGetInnerStatusEnum[keyof typeof CharactersCharacterIdMedalsGetInnerStatusEnum];


/**
 * Check if a given object implements the CharactersCharacterIdMedalsGetInner interface.
 */
export function instanceOfCharactersCharacterIdMedalsGetInner(value: object): value is CharactersCharacterIdMedalsGetInner {
    if (!('corporationId' in value) || value['corporationId'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('graphics' in value) || value['graphics'] === undefined) return false;
    if (!('issuerId' in value) || value['issuerId'] === undefined) return false;
    if (!('medalId' in value) || value['medalId'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function CharactersCharacterIdMedalsGetInnerFromJSON(json: any): CharactersCharacterIdMedalsGetInner {
    return CharactersCharacterIdMedalsGetInnerFromJSONTyped(json, false);
}

export function CharactersCharacterIdMedalsGetInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CharactersCharacterIdMedalsGetInner {
    if (json == null) {
        return json;
    }
    return {
        
        'corporationId': json['corporation_id'],
        'date': (new Date(json['date'])),
        'description': json['description'],
        'graphics': ((json['graphics'] as Array<any>).map(CharactersCharacterIdMedalsGetInnerGraphicsInnerFromJSON)),
        'issuerId': json['issuer_id'],
        'medalId': json['medal_id'],
        'reason': json['reason'],
        'status': json['status'],
        'title': json['title'],
    };
}

export function CharactersCharacterIdMedalsGetInnerToJSON(json: any): CharactersCharacterIdMedalsGetInner {
    return CharactersCharacterIdMedalsGetInnerToJSONTyped(json, false);
}

export function CharactersCharacterIdMedalsGetInnerToJSONTyped(value?: CharactersCharacterIdMedalsGetInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'corporation_id': value['corporationId'],
        'date': ((value['date']).toISOString()),
        'description': value['description'],
        'graphics': ((value['graphics'] as Array<any>).map(CharactersCharacterIdMedalsGetInnerGraphicsInnerToJSON)),
        'issuer_id': value['issuerId'],
        'medal_id': value['medalId'],
        'reason': value['reason'],
        'status': value['status'],
        'title': value['title'],
    };
}

