/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CharactersCharacterIdSkillsGetSkillsInner } from './CharactersCharacterIdSkillsGetSkillsInner';
import {
    CharactersCharacterIdSkillsGetSkillsInnerFromJSON,
    CharactersCharacterIdSkillsGetSkillsInnerFromJSONTyped,
    CharactersCharacterIdSkillsGetSkillsInnerToJSON,
    CharactersCharacterIdSkillsGetSkillsInnerToJSONTyped,
} from './CharactersCharacterIdSkillsGetSkillsInner';

/**
 * 
 * @export
 * @interface CharactersCharacterIdSkillsGet
 */
export interface CharactersCharacterIdSkillsGet {
    /**
     * 
     * @type {Array<CharactersCharacterIdSkillsGetSkillsInner>}
     * @memberof CharactersCharacterIdSkillsGet
     */
    skills: Array<CharactersCharacterIdSkillsGetSkillsInner>;
    /**
     * 
     * @type {number}
     * @memberof CharactersCharacterIdSkillsGet
     */
    totalSp: number;
    /**
     * Skill points available to be assigned
     * @type {number}
     * @memberof CharactersCharacterIdSkillsGet
     */
    unallocatedSp?: number;
}

/**
 * Check if a given object implements the CharactersCharacterIdSkillsGet interface.
 */
export function instanceOfCharactersCharacterIdSkillsGet(value: object): value is CharactersCharacterIdSkillsGet {
    if (!('skills' in value) || value['skills'] === undefined) return false;
    if (!('totalSp' in value) || value['totalSp'] === undefined) return false;
    return true;
}

export function CharactersCharacterIdSkillsGetFromJSON(json: any): CharactersCharacterIdSkillsGet {
    return CharactersCharacterIdSkillsGetFromJSONTyped(json, false);
}

export function CharactersCharacterIdSkillsGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): CharactersCharacterIdSkillsGet {
    if (json == null) {
        return json;
    }
    return {
        
        'skills': ((json['skills'] as Array<any>).map(CharactersCharacterIdSkillsGetSkillsInnerFromJSON)),
        'totalSp': json['total_sp'],
        'unallocatedSp': json['unallocated_sp'] == null ? undefined : json['unallocated_sp'],
    };
}

export function CharactersCharacterIdSkillsGetToJSON(json: any): CharactersCharacterIdSkillsGet {
    return CharactersCharacterIdSkillsGetToJSONTyped(json, false);
}

export function CharactersCharacterIdSkillsGetToJSONTyped(value?: CharactersCharacterIdSkillsGet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'skills': ((value['skills'] as Array<any>).map(CharactersCharacterIdSkillsGetSkillsInnerToJSON)),
        'total_sp': value['totalSp'],
        'unallocated_sp': value['unallocatedSp'],
    };
}

