/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 201 created object
 * @export
 * @interface CharactersCharacterIdFittingsPost
 */
export interface CharactersCharacterIdFittingsPost {
    /**
     * 
     * @type {number}
     * @memberof CharactersCharacterIdFittingsPost
     */
    fittingId: number;
}

/**
 * Check if a given object implements the CharactersCharacterIdFittingsPost interface.
 */
export function instanceOfCharactersCharacterIdFittingsPost(value: object): value is CharactersCharacterIdFittingsPost {
    if (!('fittingId' in value) || value['fittingId'] === undefined) return false;
    return true;
}

export function CharactersCharacterIdFittingsPostFromJSON(json: any): CharactersCharacterIdFittingsPost {
    return CharactersCharacterIdFittingsPostFromJSONTyped(json, false);
}

export function CharactersCharacterIdFittingsPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): CharactersCharacterIdFittingsPost {
    if (json == null) {
        return json;
    }
    return {
        
        'fittingId': json['fitting_id'],
    };
}

export function CharactersCharacterIdFittingsPostToJSON(json: any): CharactersCharacterIdFittingsPost {
    return CharactersCharacterIdFittingsPostToJSONTyped(json, false);
}

export function CharactersCharacterIdFittingsPostToJSONTyped(value?: CharactersCharacterIdFittingsPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fitting_id': value['fittingId'],
    };
}

