/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * label object
 * @export
 * @interface CharactersCharacterIdMailLabelsGetLabelsInner
 */
export interface CharactersCharacterIdMailLabelsGetLabelsInner {
    /**
     * 
     * @type {string}
     * @memberof CharactersCharacterIdMailLabelsGetLabelsInner
     */
    color?: CharactersCharacterIdMailLabelsGetLabelsInnerColorEnum;
    /**
     * 
     * @type {number}
     * @memberof CharactersCharacterIdMailLabelsGetLabelsInner
     */
    labelId?: number;
    /**
     * 
     * @type {string}
     * @memberof CharactersCharacterIdMailLabelsGetLabelsInner
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof CharactersCharacterIdMailLabelsGetLabelsInner
     */
    unreadCount?: number;
}


/**
 * @export
 */
export const CharactersCharacterIdMailLabelsGetLabelsInnerColorEnum = {
    _0000fe: '#0000fe',
    _006634: '#006634',
    _0099ff: '#0099ff',
    _00ff33: '#00ff33',
    _01ffff: '#01ffff',
    _349800: '#349800',
    _660066: '#660066',
    _666666: '#666666',
    _999999: '#999999',
    _99ffff: '#99ffff',
    _9a0000: '#9a0000',
    Ccff9a: '#ccff9a',
    E6e6e6: '#e6e6e6',
    Fe0000: '#fe0000',
    Ff6600: '#ff6600',
    Ffff01: '#ffff01',
    Ffffcd: '#ffffcd',
    Ffffff: '#ffffff'
} as const;
export type CharactersCharacterIdMailLabelsGetLabelsInnerColorEnum = typeof CharactersCharacterIdMailLabelsGetLabelsInnerColorEnum[keyof typeof CharactersCharacterIdMailLabelsGetLabelsInnerColorEnum];


/**
 * Check if a given object implements the CharactersCharacterIdMailLabelsGetLabelsInner interface.
 */
export function instanceOfCharactersCharacterIdMailLabelsGetLabelsInner(value: object): value is CharactersCharacterIdMailLabelsGetLabelsInner {
    return true;
}

export function CharactersCharacterIdMailLabelsGetLabelsInnerFromJSON(json: any): CharactersCharacterIdMailLabelsGetLabelsInner {
    return CharactersCharacterIdMailLabelsGetLabelsInnerFromJSONTyped(json, false);
}

export function CharactersCharacterIdMailLabelsGetLabelsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CharactersCharacterIdMailLabelsGetLabelsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'color': json['color'] == null ? undefined : json['color'],
        'labelId': json['label_id'] == null ? undefined : json['label_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'unreadCount': json['unread_count'] == null ? undefined : json['unread_count'],
    };
}

export function CharactersCharacterIdMailLabelsGetLabelsInnerToJSON(json: any): CharactersCharacterIdMailLabelsGetLabelsInner {
    return CharactersCharacterIdMailLabelsGetLabelsInnerToJSONTyped(json, false);
}

export function CharactersCharacterIdMailLabelsGetLabelsInnerToJSONTyped(value?: CharactersCharacterIdMailLabelsGetLabelsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'color': value['color'],
        'label_id': value['labelId'],
        'name': value['name'],
        'unread_count': value['unreadCount'],
    };
}

