/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CharactersCharacterIdOnlineGet
 */
export interface CharactersCharacterIdOnlineGet {
    /**
     * Timestamp of the last login
     * @type {Date}
     * @memberof CharactersCharacterIdOnlineGet
     */
    lastLogin?: Date;
    /**
     * Timestamp of the last logout
     * @type {Date}
     * @memberof CharactersCharacterIdOnlineGet
     */
    lastLogout?: Date;
    /**
     * Total number of times the character has logged in
     * @type {number}
     * @memberof CharactersCharacterIdOnlineGet
     */
    logins?: number;
    /**
     * If the character is online
     * @type {boolean}
     * @memberof CharactersCharacterIdOnlineGet
     */
    online: boolean;
}

/**
 * Check if a given object implements the CharactersCharacterIdOnlineGet interface.
 */
export function instanceOfCharactersCharacterIdOnlineGet(value: object): value is CharactersCharacterIdOnlineGet {
    if (!('online' in value) || value['online'] === undefined) return false;
    return true;
}

export function CharactersCharacterIdOnlineGetFromJSON(json: any): CharactersCharacterIdOnlineGet {
    return CharactersCharacterIdOnlineGetFromJSONTyped(json, false);
}

export function CharactersCharacterIdOnlineGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): CharactersCharacterIdOnlineGet {
    if (json == null) {
        return json;
    }
    return {
        
        'lastLogin': json['last_login'] == null ? undefined : (new Date(json['last_login'])),
        'lastLogout': json['last_logout'] == null ? undefined : (new Date(json['last_logout'])),
        'logins': json['logins'] == null ? undefined : json['logins'],
        'online': json['online'],
    };
}

export function CharactersCharacterIdOnlineGetToJSON(json: any): CharactersCharacterIdOnlineGet {
    return CharactersCharacterIdOnlineGetToJSONTyped(json, false);
}

export function CharactersCharacterIdOnlineGetToJSONTyped(value?: CharactersCharacterIdOnlineGet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'last_login': value['lastLogin'] == null ? undefined : ((value['lastLogin']).toISOString()),
        'last_logout': value['lastLogout'] == null ? undefined : ((value['lastLogout']).toISOString()),
        'logins': value['logins'],
        'online': value['online'],
    };
}

