/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FreelanceJobsDetailParametercorporationitemdelivery } from './FreelanceJobsDetailParametercorporationitemdelivery';
import {
    FreelanceJobsDetailParametercorporationitemdeliveryFromJSON,
    FreelanceJobsDetailParametercorporationitemdeliveryFromJSONTyped,
    FreelanceJobsDetailParametercorporationitemdeliveryToJSON,
    FreelanceJobsDetailParametercorporationitemdeliveryToJSONTyped,
} from './FreelanceJobsDetailParametercorporationitemdelivery';

/**
 * 
 * @export
 * @interface CorporationItemDelivery
 */
export interface CorporationItemDelivery {
    /**
     * Parameter for delivering items to a corporation
     * @type {FreelanceJobsDetailParametercorporationitemdelivery}
     * @memberof CorporationItemDelivery
     */
    corporationItemDelivery?: FreelanceJobsDetailParametercorporationitemdelivery;
}

/**
 * Check if a given object implements the CorporationItemDelivery interface.
 */
export function instanceOfCorporationItemDelivery(value: object): value is CorporationItemDelivery {
    return true;
}

export function CorporationItemDeliveryFromJSON(json: any): CorporationItemDelivery {
    return CorporationItemDeliveryFromJSONTyped(json, false);
}

export function CorporationItemDeliveryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorporationItemDelivery {
    if (json == null) {
        return json;
    }
    return {
        
        'corporationItemDelivery': json['corporation_item_delivery'] == null ? undefined : FreelanceJobsDetailParametercorporationitemdeliveryFromJSON(json['corporation_item_delivery']),
    };
}

export function CorporationItemDeliveryToJSON(json: any): CorporationItemDelivery {
    return CorporationItemDeliveryToJSONTyped(json, false);
}

export function CorporationItemDeliveryToJSONTyped(value?: CorporationItemDelivery | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'corporation_item_delivery': FreelanceJobsDetailParametercorporationitemdeliveryToJSON(value['corporationItemDelivery']),
    };
}

