/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CorporationsProjectsContribution
 */
export interface CorporationsProjectsContribution {
    /**
     * Your contribution
     * @type {number}
     * @memberof CorporationsProjectsContribution
     */
    contributed: number;
    /**
     * Moment this information was last modified
     * @type {Date}
     * @memberof CorporationsProjectsContribution
     */
    lastModified?: Date;
}

/**
 * Check if a given object implements the CorporationsProjectsContribution interface.
 */
export function instanceOfCorporationsProjectsContribution(value: object): value is CorporationsProjectsContribution {
    if (!('contributed' in value) || value['contributed'] === undefined) return false;
    return true;
}

export function CorporationsProjectsContributionFromJSON(json: any): CorporationsProjectsContribution {
    return CorporationsProjectsContributionFromJSONTyped(json, false);
}

export function CorporationsProjectsContributionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorporationsProjectsContribution {
    if (json == null) {
        return json;
    }
    return {
        
        'contributed': json['contributed'],
        'lastModified': json['last_modified'] == null ? undefined : (new Date(json['last_modified'])),
    };
}

export function CorporationsProjectsContributionToJSON(json: any): CorporationsProjectsContribution {
    return CorporationsProjectsContributionToJSONTyped(json, false);
}

export function CorporationsProjectsContributionToJSONTyped(value?: CorporationsProjectsContribution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contributed': value['contributed'],
        'last_modified': value['lastModified'] == null ? undefined : ((value['lastModified']).toISOString()),
    };
}

