/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CorporationsFreelanceJobsParticipantsParticipant } from './CorporationsFreelanceJobsParticipantsParticipant';
import {
    CorporationsFreelanceJobsParticipantsParticipantFromJSON,
    CorporationsFreelanceJobsParticipantsParticipantFromJSONTyped,
    CorporationsFreelanceJobsParticipantsParticipantToJSON,
    CorporationsFreelanceJobsParticipantsParticipantToJSONTyped,
} from './CorporationsFreelanceJobsParticipantsParticipant';
import type { Cursor } from './Cursor';
import {
    CursorFromJSON,
    CursorFromJSONTyped,
    CursorToJSON,
    CursorToJSONTyped,
} from './Cursor';

/**
 * 
 * @export
 * @interface CorporationsFreelanceJobsParticipants
 */
export interface CorporationsFreelanceJobsParticipants {
    /**
     * 
     * @type {Cursor}
     * @memberof CorporationsFreelanceJobsParticipants
     */
    cursor?: Cursor;
    /**
     * List of participants
     * @type {Array<CorporationsFreelanceJobsParticipantsParticipant>}
     * @memberof CorporationsFreelanceJobsParticipants
     */
    participants: Array<CorporationsFreelanceJobsParticipantsParticipant>;
}

/**
 * Check if a given object implements the CorporationsFreelanceJobsParticipants interface.
 */
export function instanceOfCorporationsFreelanceJobsParticipants(value: object): value is CorporationsFreelanceJobsParticipants {
    if (!('participants' in value) || value['participants'] === undefined) return false;
    return true;
}

export function CorporationsFreelanceJobsParticipantsFromJSON(json: any): CorporationsFreelanceJobsParticipants {
    return CorporationsFreelanceJobsParticipantsFromJSONTyped(json, false);
}

export function CorporationsFreelanceJobsParticipantsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorporationsFreelanceJobsParticipants {
    if (json == null) {
        return json;
    }
    return {
        
        'cursor': json['cursor'] == null ? undefined : CursorFromJSON(json['cursor']),
        'participants': ((json['participants'] as Array<any>).map(CorporationsFreelanceJobsParticipantsParticipantFromJSON)),
    };
}

export function CorporationsFreelanceJobsParticipantsToJSON(json: any): CorporationsFreelanceJobsParticipants {
    return CorporationsFreelanceJobsParticipantsToJSONTyped(json, false);
}

export function CorporationsFreelanceJobsParticipantsToJSONTyped(value?: CorporationsFreelanceJobsParticipants | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cursor': CursorToJSON(value['cursor']),
        'participants': ((value['participants'] as Array<any>).map(CorporationsFreelanceJobsParticipantsParticipantToJSON)),
    };
}

