/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CorporationsProjectsDetailCreator
 */
export interface CorporationsProjectsDetailCreator {
    /**
     * 
     * @type {number}
     * @memberof CorporationsProjectsDetailCreator
     */
    id: number;
    /**
     * Creator's name
     * @type {string}
     * @memberof CorporationsProjectsDetailCreator
     */
    name: string;
}

/**
 * Check if a given object implements the CorporationsProjectsDetailCreator interface.
 */
export function instanceOfCorporationsProjectsDetailCreator(value: object): value is CorporationsProjectsDetailCreator {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CorporationsProjectsDetailCreatorFromJSON(json: any): CorporationsProjectsDetailCreator {
    return CorporationsProjectsDetailCreatorFromJSONTyped(json, false);
}

export function CorporationsProjectsDetailCreatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorporationsProjectsDetailCreator {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function CorporationsProjectsDetailCreatorToJSON(json: any): CorporationsProjectsDetailCreator {
    return CorporationsProjectsDetailCreatorToJSONTyped(json, false);
}

export function CorporationsProjectsDetailCreatorToJSONTyped(value?: CorporationsProjectsDetailCreator | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

