/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Not found
 * @export
 * @interface DeleteFleetsFleetIdWingsWingIdNotFound
 */
export interface DeleteFleetsFleetIdWingsWingIdNotFound {
    /**
     * Not found message
     * @type {string}
     * @memberof DeleteFleetsFleetIdWingsWingIdNotFound
     */
    error?: string;
}

/**
 * Check if a given object implements the DeleteFleetsFleetIdWingsWingIdNotFound interface.
 */
export function instanceOfDeleteFleetsFleetIdWingsWingIdNotFound(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DeleteFleetsFleetIdWingsWingIdNotFoundFromJSON(json: any): DeleteFleetsFleetIdWingsWingIdNotFound {
    return DeleteFleetsFleetIdWingsWingIdNotFoundFromJSONTyped(json, false);
}

export function DeleteFleetsFleetIdWingsWingIdNotFoundFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteFleetsFleetIdWingsWingIdNotFound {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : json['error'],
    };
}

export function DeleteFleetsFleetIdWingsWingIdNotFoundToJSON(value?: DeleteFleetsFleetIdWingsWingIdNotFound | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': value.error,
    };
}

