/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DogmaAttributesAttributeIdGet
 */
export interface DogmaAttributesAttributeIdGet {
    /**
     * 
     * @type {number}
     * @memberof DogmaAttributesAttributeIdGet
     */
    attributeId: number;
    /**
     * 
     * @type {number}
     * @memberof DogmaAttributesAttributeIdGet
     */
    defaultValue?: number;
    /**
     * 
     * @type {string}
     * @memberof DogmaAttributesAttributeIdGet
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof DogmaAttributesAttributeIdGet
     */
    displayName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DogmaAttributesAttributeIdGet
     */
    highIsGood?: boolean;
    /**
     * 
     * @type {number}
     * @memberof DogmaAttributesAttributeIdGet
     */
    iconId?: number;
    /**
     * 
     * @type {string}
     * @memberof DogmaAttributesAttributeIdGet
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DogmaAttributesAttributeIdGet
     */
    published?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DogmaAttributesAttributeIdGet
     */
    stackable?: boolean;
    /**
     * 
     * @type {number}
     * @memberof DogmaAttributesAttributeIdGet
     */
    unitId?: number;
}

/**
 * Check if a given object implements the DogmaAttributesAttributeIdGet interface.
 */
export function instanceOfDogmaAttributesAttributeIdGet(value: object): value is DogmaAttributesAttributeIdGet {
    if (!('attributeId' in value) || value['attributeId'] === undefined) return false;
    return true;
}

export function DogmaAttributesAttributeIdGetFromJSON(json: any): DogmaAttributesAttributeIdGet {
    return DogmaAttributesAttributeIdGetFromJSONTyped(json, false);
}

export function DogmaAttributesAttributeIdGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): DogmaAttributesAttributeIdGet {
    if (json == null) {
        return json;
    }
    return {
        
        'attributeId': json['attribute_id'],
        'defaultValue': json['default_value'] == null ? undefined : json['default_value'],
        'description': json['description'] == null ? undefined : json['description'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'highIsGood': json['high_is_good'] == null ? undefined : json['high_is_good'],
        'iconId': json['icon_id'] == null ? undefined : json['icon_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'published': json['published'] == null ? undefined : json['published'],
        'stackable': json['stackable'] == null ? undefined : json['stackable'],
        'unitId': json['unit_id'] == null ? undefined : json['unit_id'],
    };
}

export function DogmaAttributesAttributeIdGetToJSON(json: any): DogmaAttributesAttributeIdGet {
    return DogmaAttributesAttributeIdGetToJSONTyped(json, false);
}

export function DogmaAttributesAttributeIdGetToJSONTyped(value?: DogmaAttributesAttributeIdGet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attribute_id': value['attributeId'],
        'default_value': value['defaultValue'],
        'description': value['description'],
        'display_name': value['displayName'],
        'high_is_good': value['highIsGood'],
        'icon_id': value['iconId'],
        'name': value['name'],
        'published': value['published'],
        'stackable': value['stackable'],
        'unit_id': value['unitId'],
    };
}

