/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stroopwafel Ingestion (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EsiAlliancesAllianceIdContactsGetInner
 */
export interface EsiAlliancesAllianceIdContactsGetInner {
    /**
     * 
     * @type {number}
     * @memberof EsiAlliancesAllianceIdContactsGetInner
     */
    contactId: number;
    /**
     * 
     * @type {string}
     * @memberof EsiAlliancesAllianceIdContactsGetInner
     */
    contactType: EsiAlliancesAllianceIdContactsGetInnerContactTypeEnum;
    /**
     * 
     * @type {Array<number>}
     * @memberof EsiAlliancesAllianceIdContactsGetInner
     */
    labelIds?: Array<number>;
    /**
     * Standing of the contact
     * @type {number}
     * @memberof EsiAlliancesAllianceIdContactsGetInner
     */
    standing: number;
}


/**
 * @export
 */
export const EsiAlliancesAllianceIdContactsGetInnerContactTypeEnum = {
    Character: 'character',
    Corporation: 'corporation',
    Alliance: 'alliance',
    Faction: 'faction'
} as const;
export type EsiAlliancesAllianceIdContactsGetInnerContactTypeEnum = typeof EsiAlliancesAllianceIdContactsGetInnerContactTypeEnum[keyof typeof EsiAlliancesAllianceIdContactsGetInnerContactTypeEnum];


/**
 * Check if a given object implements the EsiAlliancesAllianceIdContactsGetInner interface.
 */
export function instanceOfEsiAlliancesAllianceIdContactsGetInner(value: object): value is EsiAlliancesAllianceIdContactsGetInner {
    if (!('contactId' in value) || value['contactId'] === undefined) return false;
    if (!('contactType' in value) || value['contactType'] === undefined) return false;
    if (!('standing' in value) || value['standing'] === undefined) return false;
    return true;
}

export function EsiAlliancesAllianceIdContactsGetInnerFromJSON(json: any): EsiAlliancesAllianceIdContactsGetInner {
    return EsiAlliancesAllianceIdContactsGetInnerFromJSONTyped(json, false);
}

export function EsiAlliancesAllianceIdContactsGetInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): EsiAlliancesAllianceIdContactsGetInner {
    if (json == null) {
        return json;
    }
    return {
        
        'contactId': json['contact_id'],
        'contactType': json['contact_type'],
        'labelIds': json['label_ids'] == null ? undefined : json['label_ids'],
        'standing': json['standing'],
    };
}

export function EsiAlliancesAllianceIdContactsGetInnerToJSON(json: any): EsiAlliancesAllianceIdContactsGetInner {
    return EsiAlliancesAllianceIdContactsGetInnerToJSONTyped(json, false);
}

export function EsiAlliancesAllianceIdContactsGetInnerToJSONTyped(value?: EsiAlliancesAllianceIdContactsGetInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contact_id': value['contactId'],
        'contact_type': value['contactType'],
        'label_ids': value['labelIds'],
        'standing': value['standing'],
    };
}

