/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stroopwafel Ingestion (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EsiCharactersCharacterIdFleetGet
 */
export interface EsiCharactersCharacterIdFleetGet {
    /**
     * Character ID of the current fleet boss
     * @type {number}
     * @memberof EsiCharactersCharacterIdFleetGet
     */
    fleetBossId: number;
    /**
     * The character's current fleet ID
     * @type {number}
     * @memberof EsiCharactersCharacterIdFleetGet
     */
    fleetId: number;
    /**
     * Member’s role in fleet
     * @type {string}
     * @memberof EsiCharactersCharacterIdFleetGet
     */
    role: EsiCharactersCharacterIdFleetGetRoleEnum;
    /**
     * ID of the squad the member is in. If not applicable, will be set to -1
     * @type {number}
     * @memberof EsiCharactersCharacterIdFleetGet
     */
    squadId: number;
    /**
     * ID of the wing the member is in. If not applicable, will be set to -1
     * @type {number}
     * @memberof EsiCharactersCharacterIdFleetGet
     */
    wingId: number;
}


/**
 * @export
 */
export const EsiCharactersCharacterIdFleetGetRoleEnum = {
    FleetCommander: 'fleet_commander',
    SquadCommander: 'squad_commander',
    SquadMember: 'squad_member',
    WingCommander: 'wing_commander'
} as const;
export type EsiCharactersCharacterIdFleetGetRoleEnum = typeof EsiCharactersCharacterIdFleetGetRoleEnum[keyof typeof EsiCharactersCharacterIdFleetGetRoleEnum];


/**
 * Check if a given object implements the EsiCharactersCharacterIdFleetGet interface.
 */
export function instanceOfEsiCharactersCharacterIdFleetGet(value: object): value is EsiCharactersCharacterIdFleetGet {
    if (!('fleetBossId' in value) || value['fleetBossId'] === undefined) return false;
    if (!('fleetId' in value) || value['fleetId'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('squadId' in value) || value['squadId'] === undefined) return false;
    if (!('wingId' in value) || value['wingId'] === undefined) return false;
    return true;
}

export function EsiCharactersCharacterIdFleetGetFromJSON(json: any): EsiCharactersCharacterIdFleetGet {
    return EsiCharactersCharacterIdFleetGetFromJSONTyped(json, false);
}

export function EsiCharactersCharacterIdFleetGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): EsiCharactersCharacterIdFleetGet {
    if (json == null) {
        return json;
    }
    return {
        
        'fleetBossId': json['fleet_boss_id'],
        'fleetId': json['fleet_id'],
        'role': json['role'],
        'squadId': json['squad_id'],
        'wingId': json['wing_id'],
    };
}

export function EsiCharactersCharacterIdFleetGetToJSON(json: any): EsiCharactersCharacterIdFleetGet {
    return EsiCharactersCharacterIdFleetGetToJSONTyped(json, false);
}

export function EsiCharactersCharacterIdFleetGetToJSONTyped(value?: EsiCharactersCharacterIdFleetGet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fleet_boss_id': value['fleetBossId'],
        'fleet_id': value['fleetId'],
        'role': value['role'],
        'squad_id': value['squadId'],
        'wing_id': value['wingId'],
    };
}

