/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stroopwafel Ingestion (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EsiCorporationId
 */
export interface EsiCorporationId {
    /**
     * 
     * @type {number}
     * @memberof EsiCorporationId
     */
    corporationId?: number;
}

/**
 * Check if a given object implements the EsiCorporationId interface.
 */
export function instanceOfEsiCorporationId(value: object): value is EsiCorporationId {
    return true;
}

export function EsiCorporationIdFromJSON(json: any): EsiCorporationId {
    return EsiCorporationIdFromJSONTyped(json, false);
}

export function EsiCorporationIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): EsiCorporationId {
    if (json == null) {
        return json;
    }
    return {
        
        'corporationId': json['corporation_id'] == null ? undefined : json['corporation_id'],
    };
}

export function EsiCorporationIdToJSON(json: any): EsiCorporationId {
    return EsiCorporationIdToJSONTyped(json, false);
}

export function EsiCorporationIdToJSONTyped(value?: EsiCorporationId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'corporation_id': value['corporationId'],
    };
}

