/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stroopwafel Ingestion (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner } from './EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner';
import {
    EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInnerFromJSON,
    EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInnerFromJSONTyped,
    EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInnerToJSON,
    EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInnerToJSONTyped,
} from './EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner';

/**
 * 
 * @export
 * @interface EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails
 */
export interface EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails {
    /**
     * in seconds
     * @type {number}
     * @memberof EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails
     */
    cycleTime?: number;
    /**
     * 
     * @type {number}
     * @memberof EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails
     */
    headRadius?: number;
    /**
     * 
     * @type {Array<EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner>}
     * @memberof EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails
     */
    heads: Array<EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner>;
    /**
     * 
     * @type {number}
     * @memberof EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails
     */
    productTypeId?: number;
    /**
     * 
     * @type {number}
     * @memberof EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails
     */
    qtyPerCycle?: number;
}

/**
 * Check if a given object implements the EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails interface.
 */
export function instanceOfEsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails(value: object): value is EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails {
    if (!('heads' in value) || value['heads'] === undefined) return false;
    return true;
}

export function EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsFromJSON(json: any): EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails {
    return EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsFromJSONTyped(json, false);
}

export function EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'cycleTime': json['cycle_time'] == null ? undefined : json['cycle_time'],
        'headRadius': json['head_radius'] == null ? undefined : json['head_radius'],
        'heads': ((json['heads'] as Array<any>).map(EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInnerFromJSON)),
        'productTypeId': json['product_type_id'] == null ? undefined : json['product_type_id'],
        'qtyPerCycle': json['qty_per_cycle'] == null ? undefined : json['qty_per_cycle'],
    };
}

export function EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsToJSON(json: any): EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails {
    return EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsToJSONTyped(json, false);
}

export function EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsToJSONTyped(value?: EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cycle_time': value['cycleTime'],
        'head_radius': value['headRadius'],
        'heads': ((value['heads'] as Array<any>).map(EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInnerToJSON)),
        'product_type_id': value['productTypeId'],
        'qty_per_cycle': value['qtyPerCycle'],
    };
}

