/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stroopwafel Ingestion (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EsiCorporationsProjectsDetailConfigurationdamageshipShipsInner } from './EsiCorporationsProjectsDetailConfigurationdamageshipShipsInner';
import {
    EsiCorporationsProjectsDetailConfigurationdamageshipShipsInnerFromJSON,
    EsiCorporationsProjectsDetailConfigurationdamageshipShipsInnerFromJSONTyped,
    EsiCorporationsProjectsDetailConfigurationdamageshipShipsInnerToJSON,
    EsiCorporationsProjectsDetailConfigurationdamageshipShipsInnerToJSONTyped,
} from './EsiCorporationsProjectsDetailConfigurationdamageshipShipsInner';
import type { EsiCorporationsProjectsDetailConfigurationdamageshipIdentitiesInner } from './EsiCorporationsProjectsDetailConfigurationdamageshipIdentitiesInner';
import {
    EsiCorporationsProjectsDetailConfigurationdamageshipIdentitiesInnerFromJSON,
    EsiCorporationsProjectsDetailConfigurationdamageshipIdentitiesInnerFromJSONTyped,
    EsiCorporationsProjectsDetailConfigurationdamageshipIdentitiesInnerToJSON,
    EsiCorporationsProjectsDetailConfigurationdamageshipIdentitiesInnerToJSONTyped,
} from './EsiCorporationsProjectsDetailConfigurationdamageshipIdentitiesInner';
import type { EsiCorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInner } from './EsiCorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInner';
import {
    EsiCorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInnerFromJSON,
    EsiCorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInnerFromJSONTyped,
    EsiCorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInnerToJSON,
    EsiCorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInnerToJSONTyped,
} from './EsiCorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInner';

/**
 * 
 * @export
 * @interface EsiCorporationsProjectsDetailConfigurationdamageship
 */
export interface EsiCorporationsProjectsDetailConfigurationdamageship {
    /**
     * Identity of capsuleer
     * @type {Array<EsiCorporationsProjectsDetailConfigurationdamageshipIdentitiesInner>}
     * @memberof EsiCorporationsProjectsDetailConfigurationdamageship
     */
    identities?: Array<EsiCorporationsProjectsDetailConfigurationdamageshipIdentitiesInner>;
    /**
     * Location of capsuleer's ship
     * @type {Array<EsiCorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInner>}
     * @memberof EsiCorporationsProjectsDetailConfigurationdamageship
     */
    locations?: Array<EsiCorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInner>;
    /**
     * Ship-type of capsuleer's ship
     * @type {Array<EsiCorporationsProjectsDetailConfigurationdamageshipShipsInner>}
     * @memberof EsiCorporationsProjectsDetailConfigurationdamageship
     */
    ships?: Array<EsiCorporationsProjectsDetailConfigurationdamageshipShipsInner>;
}

/**
 * Check if a given object implements the EsiCorporationsProjectsDetailConfigurationdamageship interface.
 */
export function instanceOfEsiCorporationsProjectsDetailConfigurationdamageship(value: object): value is EsiCorporationsProjectsDetailConfigurationdamageship {
    return true;
}

export function EsiCorporationsProjectsDetailConfigurationdamageshipFromJSON(json: any): EsiCorporationsProjectsDetailConfigurationdamageship {
    return EsiCorporationsProjectsDetailConfigurationdamageshipFromJSONTyped(json, false);
}

export function EsiCorporationsProjectsDetailConfigurationdamageshipFromJSONTyped(json: any, ignoreDiscriminator: boolean): EsiCorporationsProjectsDetailConfigurationdamageship {
    if (json == null) {
        return json;
    }
    return {
        
        'identities': json['identities'] == null ? undefined : ((json['identities'] as Array<any>).map(EsiCorporationsProjectsDetailConfigurationdamageshipIdentitiesInnerFromJSON)),
        'locations': json['locations'] == null ? undefined : ((json['locations'] as Array<any>).map(EsiCorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInnerFromJSON)),
        'ships': json['ships'] == null ? undefined : ((json['ships'] as Array<any>).map(EsiCorporationsProjectsDetailConfigurationdamageshipShipsInnerFromJSON)),
    };
}

export function EsiCorporationsProjectsDetailConfigurationdamageshipToJSON(json: any): EsiCorporationsProjectsDetailConfigurationdamageship {
    return EsiCorporationsProjectsDetailConfigurationdamageshipToJSONTyped(json, false);
}

export function EsiCorporationsProjectsDetailConfigurationdamageshipToJSONTyped(value?: EsiCorporationsProjectsDetailConfigurationdamageship | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'identities': value['identities'] == null ? undefined : ((value['identities'] as Array<any>).map(EsiCorporationsProjectsDetailConfigurationdamageshipIdentitiesInnerToJSON)),
        'locations': value['locations'] == null ? undefined : ((value['locations'] as Array<any>).map(EsiCorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInnerToJSON)),
        'ships': value['ships'] == null ? undefined : ((value['ships'] as Array<any>).map(EsiCorporationsProjectsDetailConfigurationdamageshipShipsInnerToJSON)),
    };
}

