/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stroopwafel Ingestion (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EsiCharactersAffiliationPostInner
 */
export interface EsiCharactersAffiliationPostInner {
    /**
     * The character's alliance ID, if their corporation is in an alliance
     * @type {number}
     * @memberof EsiCharactersAffiliationPostInner
     */
    allianceId?: number;
    /**
     * The character's ID
     * @type {number}
     * @memberof EsiCharactersAffiliationPostInner
     */
    characterId: number;
    /**
     * The character's corporation ID
     * @type {number}
     * @memberof EsiCharactersAffiliationPostInner
     */
    corporationId: number;
    /**
     * The character's faction ID, if their corporation is in a faction
     * @type {number}
     * @memberof EsiCharactersAffiliationPostInner
     */
    factionId?: number;
}

/**
 * Check if a given object implements the EsiCharactersAffiliationPostInner interface.
 */
export function instanceOfEsiCharactersAffiliationPostInner(value: object): value is EsiCharactersAffiliationPostInner {
    if (!('characterId' in value) || value['characterId'] === undefined) return false;
    if (!('corporationId' in value) || value['corporationId'] === undefined) return false;
    return true;
}

export function EsiCharactersAffiliationPostInnerFromJSON(json: any): EsiCharactersAffiliationPostInner {
    return EsiCharactersAffiliationPostInnerFromJSONTyped(json, false);
}

export function EsiCharactersAffiliationPostInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): EsiCharactersAffiliationPostInner {
    if (json == null) {
        return json;
    }
    return {
        
        'allianceId': json['alliance_id'] == null ? undefined : json['alliance_id'],
        'characterId': json['character_id'],
        'corporationId': json['corporation_id'],
        'factionId': json['faction_id'] == null ? undefined : json['faction_id'],
    };
}

export function EsiCharactersAffiliationPostInnerToJSON(json: any): EsiCharactersAffiliationPostInner {
    return EsiCharactersAffiliationPostInnerToJSONTyped(json, false);
}

export function EsiCharactersAffiliationPostInnerToJSONTyped(value?: EsiCharactersAffiliationPostInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alliance_id': value['allianceId'],
        'character_id': value['characterId'],
        'corporation_id': value['corporationId'],
        'faction_id': value['factionId'],
    };
}

