/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stroopwafel Ingestion (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EsiCharactersCharacterIdPlanetsPlanetIdGetRoutesInner } from './EsiCharactersCharacterIdPlanetsPlanetIdGetRoutesInner';
import {
    EsiCharactersCharacterIdPlanetsPlanetIdGetRoutesInnerFromJSON,
    EsiCharactersCharacterIdPlanetsPlanetIdGetRoutesInnerFromJSONTyped,
    EsiCharactersCharacterIdPlanetsPlanetIdGetRoutesInnerToJSON,
    EsiCharactersCharacterIdPlanetsPlanetIdGetRoutesInnerToJSONTyped,
} from './EsiCharactersCharacterIdPlanetsPlanetIdGetRoutesInner';
import type { EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInner } from './EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInner';
import {
    EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerFromJSON,
    EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerFromJSONTyped,
    EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerToJSON,
    EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerToJSONTyped,
} from './EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInner';
import type { EsiCharactersCharacterIdPlanetsPlanetIdGetLinksInner } from './EsiCharactersCharacterIdPlanetsPlanetIdGetLinksInner';
import {
    EsiCharactersCharacterIdPlanetsPlanetIdGetLinksInnerFromJSON,
    EsiCharactersCharacterIdPlanetsPlanetIdGetLinksInnerFromJSONTyped,
    EsiCharactersCharacterIdPlanetsPlanetIdGetLinksInnerToJSON,
    EsiCharactersCharacterIdPlanetsPlanetIdGetLinksInnerToJSONTyped,
} from './EsiCharactersCharacterIdPlanetsPlanetIdGetLinksInner';

/**
 * 
 * @export
 * @interface EsiCharactersCharacterIdPlanetsPlanetIdGet
 */
export interface EsiCharactersCharacterIdPlanetsPlanetIdGet {
    /**
     * 
     * @type {Array<EsiCharactersCharacterIdPlanetsPlanetIdGetLinksInner>}
     * @memberof EsiCharactersCharacterIdPlanetsPlanetIdGet
     */
    links: Array<EsiCharactersCharacterIdPlanetsPlanetIdGetLinksInner>;
    /**
     * 
     * @type {Array<EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInner>}
     * @memberof EsiCharactersCharacterIdPlanetsPlanetIdGet
     */
    pins: Array<EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInner>;
    /**
     * 
     * @type {Array<EsiCharactersCharacterIdPlanetsPlanetIdGetRoutesInner>}
     * @memberof EsiCharactersCharacterIdPlanetsPlanetIdGet
     */
    routes: Array<EsiCharactersCharacterIdPlanetsPlanetIdGetRoutesInner>;
}

/**
 * Check if a given object implements the EsiCharactersCharacterIdPlanetsPlanetIdGet interface.
 */
export function instanceOfEsiCharactersCharacterIdPlanetsPlanetIdGet(value: object): value is EsiCharactersCharacterIdPlanetsPlanetIdGet {
    if (!('links' in value) || value['links'] === undefined) return false;
    if (!('pins' in value) || value['pins'] === undefined) return false;
    if (!('routes' in value) || value['routes'] === undefined) return false;
    return true;
}

export function EsiCharactersCharacterIdPlanetsPlanetIdGetFromJSON(json: any): EsiCharactersCharacterIdPlanetsPlanetIdGet {
    return EsiCharactersCharacterIdPlanetsPlanetIdGetFromJSONTyped(json, false);
}

export function EsiCharactersCharacterIdPlanetsPlanetIdGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): EsiCharactersCharacterIdPlanetsPlanetIdGet {
    if (json == null) {
        return json;
    }
    return {
        
        'links': ((json['links'] as Array<any>).map(EsiCharactersCharacterIdPlanetsPlanetIdGetLinksInnerFromJSON)),
        'pins': ((json['pins'] as Array<any>).map(EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerFromJSON)),
        'routes': ((json['routes'] as Array<any>).map(EsiCharactersCharacterIdPlanetsPlanetIdGetRoutesInnerFromJSON)),
    };
}

export function EsiCharactersCharacterIdPlanetsPlanetIdGetToJSON(json: any): EsiCharactersCharacterIdPlanetsPlanetIdGet {
    return EsiCharactersCharacterIdPlanetsPlanetIdGetToJSONTyped(json, false);
}

export function EsiCharactersCharacterIdPlanetsPlanetIdGetToJSONTyped(value?: EsiCharactersCharacterIdPlanetsPlanetIdGet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'links': ((value['links'] as Array<any>).map(EsiCharactersCharacterIdPlanetsPlanetIdGetLinksInnerToJSON)),
        'pins': ((value['pins'] as Array<any>).map(EsiCharactersCharacterIdPlanetsPlanetIdGetPinsInnerToJSON)),
        'routes': ((value['routes'] as Array<any>).map(EsiCharactersCharacterIdPlanetsPlanetIdGetRoutesInnerToJSON)),
    };
}

