/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stroopwafel Ingestion (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EsiContractsPublicBidsContractIdGetInner
 */
export interface EsiContractsPublicBidsContractIdGetInner {
    /**
     * The amount bid, in ISK
     * @type {number}
     * @memberof EsiContractsPublicBidsContractIdGetInner
     */
    amount: number;
    /**
     * Unique ID for the bid
     * @type {number}
     * @memberof EsiContractsPublicBidsContractIdGetInner
     */
    bidId: number;
    /**
     * Datetime when the bid was placed
     * @type {Date}
     * @memberof EsiContractsPublicBidsContractIdGetInner
     */
    dateBid: Date;
}

/**
 * Check if a given object implements the EsiContractsPublicBidsContractIdGetInner interface.
 */
export function instanceOfEsiContractsPublicBidsContractIdGetInner(value: object): value is EsiContractsPublicBidsContractIdGetInner {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('bidId' in value) || value['bidId'] === undefined) return false;
    if (!('dateBid' in value) || value['dateBid'] === undefined) return false;
    return true;
}

export function EsiContractsPublicBidsContractIdGetInnerFromJSON(json: any): EsiContractsPublicBidsContractIdGetInner {
    return EsiContractsPublicBidsContractIdGetInnerFromJSONTyped(json, false);
}

export function EsiContractsPublicBidsContractIdGetInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): EsiContractsPublicBidsContractIdGetInner {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'bidId': json['bid_id'],
        'dateBid': (new Date(json['date_bid'])),
    };
}

export function EsiContractsPublicBidsContractIdGetInnerToJSON(json: any): EsiContractsPublicBidsContractIdGetInner {
    return EsiContractsPublicBidsContractIdGetInnerToJSONTyped(json, false);
}

export function EsiContractsPublicBidsContractIdGetInnerToJSONTyped(value?: EsiContractsPublicBidsContractIdGetInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'bid_id': value['bidId'],
        'date_bid': ((value['dateBid']).toISOString()),
    };
}

