/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stroopwafel Ingestion (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * event
 * @export
 * @interface EsiCharactersCharacterIdCalendarGetInner
 */
export interface EsiCharactersCharacterIdCalendarGetInner {
    /**
     * 
     * @type {Date}
     * @memberof EsiCharactersCharacterIdCalendarGetInner
     */
    eventDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof EsiCharactersCharacterIdCalendarGetInner
     */
    eventId?: number;
    /**
     * 
     * @type {string}
     * @memberof EsiCharactersCharacterIdCalendarGetInner
     */
    eventResponse?: EsiCharactersCharacterIdCalendarGetInnerEventResponseEnum;
    /**
     * 
     * @type {number}
     * @memberof EsiCharactersCharacterIdCalendarGetInner
     */
    importance?: number;
    /**
     * 
     * @type {string}
     * @memberof EsiCharactersCharacterIdCalendarGetInner
     */
    title?: string;
}


/**
 * @export
 */
export const EsiCharactersCharacterIdCalendarGetInnerEventResponseEnum = {
    Declined: 'declined',
    NotResponded: 'not_responded',
    Accepted: 'accepted',
    Tentative: 'tentative'
} as const;
export type EsiCharactersCharacterIdCalendarGetInnerEventResponseEnum = typeof EsiCharactersCharacterIdCalendarGetInnerEventResponseEnum[keyof typeof EsiCharactersCharacterIdCalendarGetInnerEventResponseEnum];


/**
 * Check if a given object implements the EsiCharactersCharacterIdCalendarGetInner interface.
 */
export function instanceOfEsiCharactersCharacterIdCalendarGetInner(value: object): value is EsiCharactersCharacterIdCalendarGetInner {
    return true;
}

export function EsiCharactersCharacterIdCalendarGetInnerFromJSON(json: any): EsiCharactersCharacterIdCalendarGetInner {
    return EsiCharactersCharacterIdCalendarGetInnerFromJSONTyped(json, false);
}

export function EsiCharactersCharacterIdCalendarGetInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): EsiCharactersCharacterIdCalendarGetInner {
    if (json == null) {
        return json;
    }
    return {
        
        'eventDate': json['event_date'] == null ? undefined : (new Date(json['event_date'])),
        'eventId': json['event_id'] == null ? undefined : json['event_id'],
        'eventResponse': json['event_response'] == null ? undefined : json['event_response'],
        'importance': json['importance'] == null ? undefined : json['importance'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function EsiCharactersCharacterIdCalendarGetInnerToJSON(json: any): EsiCharactersCharacterIdCalendarGetInner {
    return EsiCharactersCharacterIdCalendarGetInnerToJSONTyped(json, false);
}

export function EsiCharactersCharacterIdCalendarGetInnerToJSONTyped(value?: EsiCharactersCharacterIdCalendarGetInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event_date': value['eventDate'] == null ? undefined : ((value['eventDate']).toISOString()),
        'event_id': value['eventId'],
        'event_response': value['eventResponse'],
        'importance': value['importance'],
        'title': value['title'],
    };
}

