/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stroopwafel Ingestion (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EsiCharacterId
 */
export interface EsiCharacterId {
    /**
     * 
     * @type {number}
     * @memberof EsiCharacterId
     */
    characterId?: number;
}

/**
 * Check if a given object implements the EsiCharacterId interface.
 */
export function instanceOfEsiCharacterId(value: object): value is EsiCharacterId {
    return true;
}

export function EsiCharacterIdFromJSON(json: any): EsiCharacterId {
    return EsiCharacterIdFromJSONTyped(json, false);
}

export function EsiCharacterIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): EsiCharacterId {
    if (json == null) {
        return json;
    }
    return {
        
        'characterId': json['character_id'] == null ? undefined : json['character_id'],
    };
}

export function EsiCharacterIdToJSON(json: any): EsiCharacterId {
    return EsiCharacterIdToJSONTyped(json, false);
}

export function EsiCharacterIdToJSONTyped(value?: EsiCharacterId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'character_id': value['characterId'],
    };
}

