/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stroopwafel Ingestion (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EsiGroupId1 } from './EsiGroupId1';
import {
    instanceOfEsiGroupId1,
    EsiGroupId1FromJSON,
    EsiGroupId1FromJSONTyped,
    EsiGroupId1ToJSON,
} from './EsiGroupId1';
import type { EsiTypeId } from './EsiTypeId';
import {
    instanceOfEsiTypeId,
    EsiTypeIdFromJSON,
    EsiTypeIdFromJSONTyped,
    EsiTypeIdToJSON,
} from './EsiTypeId';

/**
 * @type EsiCorporationsProjectsDetailConfigurationdeliveritemItemsInner
 * 
 * @export
 */
export type EsiCorporationsProjectsDetailConfigurationdeliveritemItemsInner = EsiGroupId1 | EsiTypeId;

export function EsiCorporationsProjectsDetailConfigurationdeliveritemItemsInnerFromJSON(json: any): EsiCorporationsProjectsDetailConfigurationdeliveritemItemsInner {
    return EsiCorporationsProjectsDetailConfigurationdeliveritemItemsInnerFromJSONTyped(json, false);
}

export function EsiCorporationsProjectsDetailConfigurationdeliveritemItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): EsiCorporationsProjectsDetailConfigurationdeliveritemItemsInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfEsiGroupId1(json)) {
        return EsiGroupId1FromJSONTyped(json, true);
    }
    if (instanceOfEsiTypeId(json)) {
        return EsiTypeIdFromJSONTyped(json, true);
    }

    return {} as any;
}

export function EsiCorporationsProjectsDetailConfigurationdeliveritemItemsInnerToJSON(json: any): any {
    return EsiCorporationsProjectsDetailConfigurationdeliveritemItemsInnerToJSONTyped(json, false);
}

export function EsiCorporationsProjectsDetailConfigurationdeliveritemItemsInnerToJSONTyped(value?: EsiCorporationsProjectsDetailConfigurationdeliveritemItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfEsiGroupId1(value)) {
        return EsiGroupId1ToJSON(value as EsiGroupId1);
    }
    if (instanceOfEsiTypeId(value)) {
        return EsiTypeIdToJSON(value as EsiTypeId);
    }

    return {};
}

