/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stroopwafel Ingestion (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EsiCorporationsProjectsDetailConfigurationdestroyship } from './EsiCorporationsProjectsDetailConfigurationdestroyship';
import {
    EsiCorporationsProjectsDetailConfigurationdestroyshipFromJSON,
    EsiCorporationsProjectsDetailConfigurationdestroyshipFromJSONTyped,
    EsiCorporationsProjectsDetailConfigurationdestroyshipToJSON,
    EsiCorporationsProjectsDetailConfigurationdestroyshipToJSONTyped,
} from './EsiCorporationsProjectsDetailConfigurationdestroyship';

/**
 * 
 * @export
 * @interface EsiDestroyShip
 */
export interface EsiDestroyShip {
    /**
     * Destroy ship
     * @type {EsiCorporationsProjectsDetailConfigurationdestroyship}
     * @memberof EsiDestroyShip
     */
    destroyShip?: EsiCorporationsProjectsDetailConfigurationdestroyship;
}

/**
 * Check if a given object implements the EsiDestroyShip interface.
 */
export function instanceOfEsiDestroyShip(value: object): value is EsiDestroyShip {
    return true;
}

export function EsiDestroyShipFromJSON(json: any): EsiDestroyShip {
    return EsiDestroyShipFromJSONTyped(json, false);
}

export function EsiDestroyShipFromJSONTyped(json: any, ignoreDiscriminator: boolean): EsiDestroyShip {
    if (json == null) {
        return json;
    }
    return {
        
        'destroyShip': json['destroy_ship'] == null ? undefined : EsiCorporationsProjectsDetailConfigurationdestroyshipFromJSON(json['destroy_ship']),
    };
}

export function EsiDestroyShipToJSON(json: any): EsiDestroyShip {
    return EsiDestroyShipToJSONTyped(json, false);
}

export function EsiDestroyShipToJSONTyped(value?: EsiDestroyShip | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'destroy_ship': EsiCorporationsProjectsDetailConfigurationdestroyshipToJSON(value['destroyShip']),
    };
}

