/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stroopwafel Ingestion (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * yesterday object
 * @export
 * @interface EsiFwLeaderboardsCharactersGetVictoryPointsYesterdayInner
 */
export interface EsiFwLeaderboardsCharactersGetVictoryPointsYesterdayInner {
    /**
     * Amount of victory points
     * @type {number}
     * @memberof EsiFwLeaderboardsCharactersGetVictoryPointsYesterdayInner
     */
    amount?: number;
    /**
     * 
     * @type {number}
     * @memberof EsiFwLeaderboardsCharactersGetVictoryPointsYesterdayInner
     */
    characterId?: number;
}

/**
 * Check if a given object implements the EsiFwLeaderboardsCharactersGetVictoryPointsYesterdayInner interface.
 */
export function instanceOfEsiFwLeaderboardsCharactersGetVictoryPointsYesterdayInner(value: object): value is EsiFwLeaderboardsCharactersGetVictoryPointsYesterdayInner {
    return true;
}

export function EsiFwLeaderboardsCharactersGetVictoryPointsYesterdayInnerFromJSON(json: any): EsiFwLeaderboardsCharactersGetVictoryPointsYesterdayInner {
    return EsiFwLeaderboardsCharactersGetVictoryPointsYesterdayInnerFromJSONTyped(json, false);
}

export function EsiFwLeaderboardsCharactersGetVictoryPointsYesterdayInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): EsiFwLeaderboardsCharactersGetVictoryPointsYesterdayInner {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'characterId': json['character_id'] == null ? undefined : json['character_id'],
    };
}

export function EsiFwLeaderboardsCharactersGetVictoryPointsYesterdayInnerToJSON(json: any): EsiFwLeaderboardsCharactersGetVictoryPointsYesterdayInner {
    return EsiFwLeaderboardsCharactersGetVictoryPointsYesterdayInnerToJSONTyped(json, false);
}

export function EsiFwLeaderboardsCharactersGetVictoryPointsYesterdayInnerToJSONTyped(value?: EsiFwLeaderboardsCharactersGetVictoryPointsYesterdayInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'character_id': value['characterId'],
    };
}

