/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stroopwafel Ingestion (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EsiCorporationItemDelivery } from './EsiCorporationItemDelivery';
import {
    instanceOfEsiCorporationItemDelivery,
    EsiCorporationItemDeliveryFromJSON,
    EsiCorporationItemDeliveryFromJSONTyped,
    EsiCorporationItemDeliveryToJSON,
} from './EsiCorporationItemDelivery';
import type { EsiMatcher } from './EsiMatcher';
import {
    instanceOfEsiMatcher,
    EsiMatcherFromJSON,
    EsiMatcherFromJSONTyped,
    EsiMatcherToJSON,
} from './EsiMatcher';
import type { EsiOptions } from './EsiOptions';
import {
    instanceOfEsiOptions,
    EsiOptionsFromJSON,
    EsiOptionsFromJSONTyped,
    EsiOptionsToJSON,
} from './EsiOptions';

/**
 * @type EsiFreelanceJobsDetailConfigurationParametersValue
 * 
 * @export
 */
export type EsiFreelanceJobsDetailConfigurationParametersValue = EsiBoolean | EsiCorporationItemDelivery | EsiMatcher | EsiOptions;

export function EsiFreelanceJobsDetailConfigurationParametersValueFromJSON(json: any): EsiFreelanceJobsDetailConfigurationParametersValue {
    return EsiFreelanceJobsDetailConfigurationParametersValueFromJSONTyped(json, false);
}

export function EsiFreelanceJobsDetailConfigurationParametersValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): EsiFreelanceJobsDetailConfigurationParametersValue {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfEsiCorporationItemDelivery(json)) {
        return EsiCorporationItemDeliveryFromJSONTyped(json, true);
    }
    if (instanceOfEsiMatcher(json)) {
        return EsiMatcherFromJSONTyped(json, true);
    }
    if (instanceOfEsiOptions(json)) {
        return EsiOptionsFromJSONTyped(json, true);
    }
    if (instanceOfboolean(json)) {
        return booleanFromJSONTyped(json, true);
    }

    return {} as any;
}

export function EsiFreelanceJobsDetailConfigurationParametersValueToJSON(json: any): any {
    return EsiFreelanceJobsDetailConfigurationParametersValueToJSONTyped(json, false);
}

export function EsiFreelanceJobsDetailConfigurationParametersValueToJSONTyped(value?: EsiFreelanceJobsDetailConfigurationParametersValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfEsiCorporationItemDelivery(value)) {
        return EsiCorporationItemDeliveryToJSON(value as EsiCorporationItemDelivery);
    }
    if (instanceOfEsiMatcher(value)) {
        return EsiMatcherToJSON(value as EsiMatcher);
    }
    if (instanceOfEsiOptions(value)) {
        return EsiOptionsToJSON(value as EsiOptions);
    }
    if (instanceOfboolean(value)) {
        return booleanToJSON(value as boolean);
    }

    return {};
}

