/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stroopwafel Ingestion (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EsiFwLeaderboardsCharactersGetKillsActiveTotalInner } from './EsiFwLeaderboardsCharactersGetKillsActiveTotalInner';
import {
    EsiFwLeaderboardsCharactersGetKillsActiveTotalInnerFromJSON,
    EsiFwLeaderboardsCharactersGetKillsActiveTotalInnerFromJSONTyped,
    EsiFwLeaderboardsCharactersGetKillsActiveTotalInnerToJSON,
    EsiFwLeaderboardsCharactersGetKillsActiveTotalInnerToJSONTyped,
} from './EsiFwLeaderboardsCharactersGetKillsActiveTotalInner';
import type { EsiFwLeaderboardsCharactersGetKillsLastWeekInner } from './EsiFwLeaderboardsCharactersGetKillsLastWeekInner';
import {
    EsiFwLeaderboardsCharactersGetKillsLastWeekInnerFromJSON,
    EsiFwLeaderboardsCharactersGetKillsLastWeekInnerFromJSONTyped,
    EsiFwLeaderboardsCharactersGetKillsLastWeekInnerToJSON,
    EsiFwLeaderboardsCharactersGetKillsLastWeekInnerToJSONTyped,
} from './EsiFwLeaderboardsCharactersGetKillsLastWeekInner';
import type { EsiFwLeaderboardsCharactersGetKillsYesterdayInner } from './EsiFwLeaderboardsCharactersGetKillsYesterdayInner';
import {
    EsiFwLeaderboardsCharactersGetKillsYesterdayInnerFromJSON,
    EsiFwLeaderboardsCharactersGetKillsYesterdayInnerFromJSONTyped,
    EsiFwLeaderboardsCharactersGetKillsYesterdayInnerToJSON,
    EsiFwLeaderboardsCharactersGetKillsYesterdayInnerToJSONTyped,
} from './EsiFwLeaderboardsCharactersGetKillsYesterdayInner';

/**
 * Top 100 rankings of pilots by number of kills from yesterday, last week and in total
 * @export
 * @interface EsiFwLeaderboardsCharactersGetKills
 */
export interface EsiFwLeaderboardsCharactersGetKills {
    /**
     * Top 100 ranking of pilots active in faction warfare by total kills. A pilot is considered "active" if they have participated in faction warfare in the past 14 days
     * @type {Array<EsiFwLeaderboardsCharactersGetKillsActiveTotalInner>}
     * @memberof EsiFwLeaderboardsCharactersGetKills
     */
    activeTotal: Array<EsiFwLeaderboardsCharactersGetKillsActiveTotalInner>;
    /**
     * Top 100 ranking of pilots by kills in the past week
     * @type {Array<EsiFwLeaderboardsCharactersGetKillsLastWeekInner>}
     * @memberof EsiFwLeaderboardsCharactersGetKills
     */
    lastWeek: Array<EsiFwLeaderboardsCharactersGetKillsLastWeekInner>;
    /**
     * Top 100 ranking of pilots by kills in the past day
     * @type {Array<EsiFwLeaderboardsCharactersGetKillsYesterdayInner>}
     * @memberof EsiFwLeaderboardsCharactersGetKills
     */
    yesterday: Array<EsiFwLeaderboardsCharactersGetKillsYesterdayInner>;
}

/**
 * Check if a given object implements the EsiFwLeaderboardsCharactersGetKills interface.
 */
export function instanceOfEsiFwLeaderboardsCharactersGetKills(value: object): value is EsiFwLeaderboardsCharactersGetKills {
    if (!('activeTotal' in value) || value['activeTotal'] === undefined) return false;
    if (!('lastWeek' in value) || value['lastWeek'] === undefined) return false;
    if (!('yesterday' in value) || value['yesterday'] === undefined) return false;
    return true;
}

export function EsiFwLeaderboardsCharactersGetKillsFromJSON(json: any): EsiFwLeaderboardsCharactersGetKills {
    return EsiFwLeaderboardsCharactersGetKillsFromJSONTyped(json, false);
}

export function EsiFwLeaderboardsCharactersGetKillsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EsiFwLeaderboardsCharactersGetKills {
    if (json == null) {
        return json;
    }
    return {
        
        'activeTotal': ((json['active_total'] as Array<any>).map(EsiFwLeaderboardsCharactersGetKillsActiveTotalInnerFromJSON)),
        'lastWeek': ((json['last_week'] as Array<any>).map(EsiFwLeaderboardsCharactersGetKillsLastWeekInnerFromJSON)),
        'yesterday': ((json['yesterday'] as Array<any>).map(EsiFwLeaderboardsCharactersGetKillsYesterdayInnerFromJSON)),
    };
}

export function EsiFwLeaderboardsCharactersGetKillsToJSON(json: any): EsiFwLeaderboardsCharactersGetKills {
    return EsiFwLeaderboardsCharactersGetKillsToJSONTyped(json, false);
}

export function EsiFwLeaderboardsCharactersGetKillsToJSONTyped(value?: EsiFwLeaderboardsCharactersGetKills | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active_total': ((value['activeTotal'] as Array<any>).map(EsiFwLeaderboardsCharactersGetKillsActiveTotalInnerToJSON)),
        'last_week': ((value['lastWeek'] as Array<any>).map(EsiFwLeaderboardsCharactersGetKillsLastWeekInnerToJSON)),
        'yesterday': ((value['yesterday'] as Array<any>).map(EsiFwLeaderboardsCharactersGetKillsYesterdayInnerToJSON)),
    };
}

