/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stroopwafel Ingestion (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EsiFreelanceJobsDetailReward } from './EsiFreelanceJobsDetailReward';
import {
    EsiFreelanceJobsDetailRewardFromJSON,
    EsiFreelanceJobsDetailRewardFromJSONTyped,
    EsiFreelanceJobsDetailRewardToJSON,
    EsiFreelanceJobsDetailRewardToJSONTyped,
} from './EsiFreelanceJobsDetailReward';
import type { EsiFreelanceJobsDetailProgress } from './EsiFreelanceJobsDetailProgress';
import {
    EsiFreelanceJobsDetailProgressFromJSON,
    EsiFreelanceJobsDetailProgressFromJSONTyped,
    EsiFreelanceJobsDetailProgressToJSON,
    EsiFreelanceJobsDetailProgressToJSONTyped,
} from './EsiFreelanceJobsDetailProgress';

/**
 * 
 * @export
 * @interface EsiFreelanceJobsDetailFreelancejob
 */
export interface EsiFreelanceJobsDetailFreelancejob {
    /**
     * 
     * @type {string}
     * @memberof EsiFreelanceJobsDetailFreelancejob
     */
    id: string;
    /**
     * Job's last modified
     * @type {Date}
     * @memberof EsiFreelanceJobsDetailFreelancejob
     */
    lastModified: Date;
    /**
     * Job's name
     * @type {string}
     * @memberof EsiFreelanceJobsDetailFreelancejob
     */
    name: string;
    /**
     * Job's progress
     * @type {EsiFreelanceJobsDetailProgress}
     * @memberof EsiFreelanceJobsDetailFreelancejob
     */
    progress: EsiFreelanceJobsDetailProgress;
    /**
     * Job's reward
     * @type {EsiFreelanceJobsDetailReward}
     * @memberof EsiFreelanceJobsDetailFreelancejob
     */
    reward?: EsiFreelanceJobsDetailReward;
    /**
     * Job's state
     * @type {string}
     * @memberof EsiFreelanceJobsDetailFreelancejob
     */
    state: EsiFreelanceJobsDetailFreelancejobStateEnum;
}


/**
 * @export
 */
export const EsiFreelanceJobsDetailFreelancejobStateEnum = {
    Unspecified: 'Unspecified',
    Active: 'Active',
    Closed: 'Closed',
    Completed: 'Completed',
    Expired: 'Expired',
    Deleted: 'Deleted'
} as const;
export type EsiFreelanceJobsDetailFreelancejobStateEnum = typeof EsiFreelanceJobsDetailFreelancejobStateEnum[keyof typeof EsiFreelanceJobsDetailFreelancejobStateEnum];


/**
 * Check if a given object implements the EsiFreelanceJobsDetailFreelancejob interface.
 */
export function instanceOfEsiFreelanceJobsDetailFreelancejob(value: object): value is EsiFreelanceJobsDetailFreelancejob {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('lastModified' in value) || value['lastModified'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('progress' in value) || value['progress'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function EsiFreelanceJobsDetailFreelancejobFromJSON(json: any): EsiFreelanceJobsDetailFreelancejob {
    return EsiFreelanceJobsDetailFreelancejobFromJSONTyped(json, false);
}

export function EsiFreelanceJobsDetailFreelancejobFromJSONTyped(json: any, ignoreDiscriminator: boolean): EsiFreelanceJobsDetailFreelancejob {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'lastModified': (new Date(json['last_modified'])),
        'name': json['name'],
        'progress': EsiFreelanceJobsDetailProgressFromJSON(json['progress']),
        'reward': json['reward'] == null ? undefined : EsiFreelanceJobsDetailRewardFromJSON(json['reward']),
        'state': json['state'],
    };
}

export function EsiFreelanceJobsDetailFreelancejobToJSON(json: any): EsiFreelanceJobsDetailFreelancejob {
    return EsiFreelanceJobsDetailFreelancejobToJSONTyped(json, false);
}

export function EsiFreelanceJobsDetailFreelancejobToJSONTyped(value?: EsiFreelanceJobsDetailFreelancejob | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'last_modified': ((value['lastModified']).toISOString()),
        'name': value['name'],
        'progress': EsiFreelanceJobsDetailProgressToJSON(value['progress']),
        'reward': EsiFreelanceJobsDetailRewardToJSON(value['reward']),
        'state': value['state'],
    };
}

