/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stroopwafel Ingestion (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * yesterday object
 * @export
 * @interface EsiFwLeaderboardsGetVictoryPointsYesterdayInner
 */
export interface EsiFwLeaderboardsGetVictoryPointsYesterdayInner {
    /**
     * Amount of victory points
     * @type {number}
     * @memberof EsiFwLeaderboardsGetVictoryPointsYesterdayInner
     */
    amount?: number;
    /**
     * 
     * @type {number}
     * @memberof EsiFwLeaderboardsGetVictoryPointsYesterdayInner
     */
    factionId?: number;
}

/**
 * Check if a given object implements the EsiFwLeaderboardsGetVictoryPointsYesterdayInner interface.
 */
export function instanceOfEsiFwLeaderboardsGetVictoryPointsYesterdayInner(value: object): value is EsiFwLeaderboardsGetVictoryPointsYesterdayInner {
    return true;
}

export function EsiFwLeaderboardsGetVictoryPointsYesterdayInnerFromJSON(json: any): EsiFwLeaderboardsGetVictoryPointsYesterdayInner {
    return EsiFwLeaderboardsGetVictoryPointsYesterdayInnerFromJSONTyped(json, false);
}

export function EsiFwLeaderboardsGetVictoryPointsYesterdayInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): EsiFwLeaderboardsGetVictoryPointsYesterdayInner {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'factionId': json['faction_id'] == null ? undefined : json['faction_id'],
    };
}

export function EsiFwLeaderboardsGetVictoryPointsYesterdayInnerToJSON(json: any): EsiFwLeaderboardsGetVictoryPointsYesterdayInner {
    return EsiFwLeaderboardsGetVictoryPointsYesterdayInnerToJSONTyped(json, false);
}

export function EsiFwLeaderboardsGetVictoryPointsYesterdayInnerToJSONTyped(value?: EsiFwLeaderboardsGetVictoryPointsYesterdayInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'faction_id': value['factionId'],
    };
}

