/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stroopwafel Ingestion (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EsiGroupId1
 */
export interface EsiGroupId1 {
    /**
     * 
     * @type {number}
     * @memberof EsiGroupId1
     */
    groupId?: number;
}

/**
 * Check if a given object implements the EsiGroupId1 interface.
 */
export function instanceOfEsiGroupId1(value: object): value is EsiGroupId1 {
    return true;
}

export function EsiGroupId1FromJSON(json: any): EsiGroupId1 {
    return EsiGroupId1FromJSONTyped(json, false);
}

export function EsiGroupId1FromJSONTyped(json: any, ignoreDiscriminator: boolean): EsiGroupId1 {
    if (json == null) {
        return json;
    }
    return {
        
        'groupId': json['group_id'] == null ? undefined : json['group_id'],
    };
}

export function EsiGroupId1ToJSON(json: any): EsiGroupId1 {
    return EsiGroupId1ToJSONTyped(json, false);
}

export function EsiGroupId1ToJSONTyped(value?: EsiGroupId1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'group_id': value['groupId'],
    };
}

