/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stroopwafel Ingestion (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * attacker object
 * @export
 * @interface EsiKillmailsKillmailIdKillmailHashGetAttackersInner
 */
export interface EsiKillmailsKillmailIdKillmailHashGetAttackersInner {
    /**
     * 
     * @type {number}
     * @memberof EsiKillmailsKillmailIdKillmailHashGetAttackersInner
     */
    allianceId?: number;
    /**
     * 
     * @type {number}
     * @memberof EsiKillmailsKillmailIdKillmailHashGetAttackersInner
     */
    characterId?: number;
    /**
     * 
     * @type {number}
     * @memberof EsiKillmailsKillmailIdKillmailHashGetAttackersInner
     */
    corporationId?: number;
    /**
     * 
     * @type {number}
     * @memberof EsiKillmailsKillmailIdKillmailHashGetAttackersInner
     */
    damageDone: number;
    /**
     * 
     * @type {number}
     * @memberof EsiKillmailsKillmailIdKillmailHashGetAttackersInner
     */
    factionId?: number;
    /**
     * Was the attacker the one to achieve the final blow
     * 
     * @type {boolean}
     * @memberof EsiKillmailsKillmailIdKillmailHashGetAttackersInner
     */
    finalBlow: boolean;
    /**
     * Security status for the attacker
     * 
     * @type {number}
     * @memberof EsiKillmailsKillmailIdKillmailHashGetAttackersInner
     */
    securityStatus: number;
    /**
     * What ship was the attacker flying
     * 
     * @type {number}
     * @memberof EsiKillmailsKillmailIdKillmailHashGetAttackersInner
     */
    shipTypeId?: number;
    /**
     * What weapon was used by the attacker for the kill
     * 
     * @type {number}
     * @memberof EsiKillmailsKillmailIdKillmailHashGetAttackersInner
     */
    weaponTypeId?: number;
}

/**
 * Check if a given object implements the EsiKillmailsKillmailIdKillmailHashGetAttackersInner interface.
 */
export function instanceOfEsiKillmailsKillmailIdKillmailHashGetAttackersInner(value: object): value is EsiKillmailsKillmailIdKillmailHashGetAttackersInner {
    if (!('damageDone' in value) || value['damageDone'] === undefined) return false;
    if (!('finalBlow' in value) || value['finalBlow'] === undefined) return false;
    if (!('securityStatus' in value) || value['securityStatus'] === undefined) return false;
    return true;
}

export function EsiKillmailsKillmailIdKillmailHashGetAttackersInnerFromJSON(json: any): EsiKillmailsKillmailIdKillmailHashGetAttackersInner {
    return EsiKillmailsKillmailIdKillmailHashGetAttackersInnerFromJSONTyped(json, false);
}

export function EsiKillmailsKillmailIdKillmailHashGetAttackersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): EsiKillmailsKillmailIdKillmailHashGetAttackersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'allianceId': json['alliance_id'] == null ? undefined : json['alliance_id'],
        'characterId': json['character_id'] == null ? undefined : json['character_id'],
        'corporationId': json['corporation_id'] == null ? undefined : json['corporation_id'],
        'damageDone': json['damage_done'],
        'factionId': json['faction_id'] == null ? undefined : json['faction_id'],
        'finalBlow': json['final_blow'],
        'securityStatus': json['security_status'],
        'shipTypeId': json['ship_type_id'] == null ? undefined : json['ship_type_id'],
        'weaponTypeId': json['weapon_type_id'] == null ? undefined : json['weapon_type_id'],
    };
}

export function EsiKillmailsKillmailIdKillmailHashGetAttackersInnerToJSON(json: any): EsiKillmailsKillmailIdKillmailHashGetAttackersInner {
    return EsiKillmailsKillmailIdKillmailHashGetAttackersInnerToJSONTyped(json, false);
}

export function EsiKillmailsKillmailIdKillmailHashGetAttackersInnerToJSONTyped(value?: EsiKillmailsKillmailIdKillmailHashGetAttackersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alliance_id': value['allianceId'],
        'character_id': value['characterId'],
        'corporation_id': value['corporationId'],
        'damage_done': value['damageDone'],
        'faction_id': value['factionId'],
        'final_blow': value['finalBlow'],
        'security_status': value['securityStatus'],
        'ship_type_id': value['shipTypeId'],
        'weapon_type_id': value['weaponTypeId'],
    };
}

