/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stroopwafel Ingestion (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EsiPutFleetsFleetIdSquadsSquadIdRequest
 */
export interface EsiPutFleetsFleetIdSquadsSquadIdRequest {
    /**
     * 
     * @type {string}
     * @memberof EsiPutFleetsFleetIdSquadsSquadIdRequest
     */
    name: string;
}

/**
 * Check if a given object implements the EsiPutFleetsFleetIdSquadsSquadIdRequest interface.
 */
export function instanceOfEsiPutFleetsFleetIdSquadsSquadIdRequest(value: object): value is EsiPutFleetsFleetIdSquadsSquadIdRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function EsiPutFleetsFleetIdSquadsSquadIdRequestFromJSON(json: any): EsiPutFleetsFleetIdSquadsSquadIdRequest {
    return EsiPutFleetsFleetIdSquadsSquadIdRequestFromJSONTyped(json, false);
}

export function EsiPutFleetsFleetIdSquadsSquadIdRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EsiPutFleetsFleetIdSquadsSquadIdRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function EsiPutFleetsFleetIdSquadsSquadIdRequestToJSON(json: any): EsiPutFleetsFleetIdSquadsSquadIdRequest {
    return EsiPutFleetsFleetIdSquadsSquadIdRequestToJSONTyped(json, false);
}

export function EsiPutFleetsFleetIdSquadsSquadIdRequestToJSONTyped(value?: EsiPutFleetsFleetIdSquadsSquadIdRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

