/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stroopwafel Ingestion (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EsiSovereigntyCampaignsGetInnerParticipantsInner } from './EsiSovereigntyCampaignsGetInnerParticipantsInner';
import {
    EsiSovereigntyCampaignsGetInnerParticipantsInnerFromJSON,
    EsiSovereigntyCampaignsGetInnerParticipantsInnerFromJSONTyped,
    EsiSovereigntyCampaignsGetInnerParticipantsInnerToJSON,
    EsiSovereigntyCampaignsGetInnerParticipantsInnerToJSONTyped,
} from './EsiSovereigntyCampaignsGetInnerParticipantsInner';

/**
 * 
 * @export
 * @interface EsiSovereigntyCampaignsGetInner
 */
export interface EsiSovereigntyCampaignsGetInner {
    /**
     * Score for all attacking parties, only present in Defense Events.
     * 
     * @type {number}
     * @memberof EsiSovereigntyCampaignsGetInner
     */
    attackersScore?: number;
    /**
     * Unique ID for this campaign.
     * @type {number}
     * @memberof EsiSovereigntyCampaignsGetInner
     */
    campaignId: number;
    /**
     * The constellation in which the campaign will take place.
     * 
     * @type {number}
     * @memberof EsiSovereigntyCampaignsGetInner
     */
    constellationId: number;
    /**
     * Defending alliance, only present in Defense Events
     * 
     * @type {number}
     * @memberof EsiSovereigntyCampaignsGetInner
     */
    defenderId?: number;
    /**
     * Score for the defending alliance, only present in Defense Events.
     * 
     * @type {number}
     * @memberof EsiSovereigntyCampaignsGetInner
     */
    defenderScore?: number;
    /**
     * Type of event this campaign is for. tcu_defense, ihub_defense and station_defense are referred to as "Defense Events", station_freeport as "Freeport Events".
     * 
     * @type {string}
     * @memberof EsiSovereigntyCampaignsGetInner
     */
    eventType: EsiSovereigntyCampaignsGetInnerEventTypeEnum;
    /**
     * Alliance participating and their respective scores, only present in Freeport Events.
     * 
     * @type {Array<EsiSovereigntyCampaignsGetInnerParticipantsInner>}
     * @memberof EsiSovereigntyCampaignsGetInner
     */
    participants?: Array<EsiSovereigntyCampaignsGetInnerParticipantsInner>;
    /**
     * The solar system the structure is located in.
     * 
     * @type {number}
     * @memberof EsiSovereigntyCampaignsGetInner
     */
    solarSystemId: number;
    /**
     * Time the event is scheduled to start.
     * 
     * @type {Date}
     * @memberof EsiSovereigntyCampaignsGetInner
     */
    startTime: Date;
    /**
     * The structure item ID that is related to this campaign.
     * 
     * @type {number}
     * @memberof EsiSovereigntyCampaignsGetInner
     */
    structureId: number;
}


/**
 * @export
 */
export const EsiSovereigntyCampaignsGetInnerEventTypeEnum = {
    TcuDefense: 'tcu_defense',
    IhubDefense: 'ihub_defense',
    StationDefense: 'station_defense',
    StationFreeport: 'station_freeport'
} as const;
export type EsiSovereigntyCampaignsGetInnerEventTypeEnum = typeof EsiSovereigntyCampaignsGetInnerEventTypeEnum[keyof typeof EsiSovereigntyCampaignsGetInnerEventTypeEnum];


/**
 * Check if a given object implements the EsiSovereigntyCampaignsGetInner interface.
 */
export function instanceOfEsiSovereigntyCampaignsGetInner(value: object): value is EsiSovereigntyCampaignsGetInner {
    if (!('campaignId' in value) || value['campaignId'] === undefined) return false;
    if (!('constellationId' in value) || value['constellationId'] === undefined) return false;
    if (!('eventType' in value) || value['eventType'] === undefined) return false;
    if (!('solarSystemId' in value) || value['solarSystemId'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('structureId' in value) || value['structureId'] === undefined) return false;
    return true;
}

export function EsiSovereigntyCampaignsGetInnerFromJSON(json: any): EsiSovereigntyCampaignsGetInner {
    return EsiSovereigntyCampaignsGetInnerFromJSONTyped(json, false);
}

export function EsiSovereigntyCampaignsGetInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): EsiSovereigntyCampaignsGetInner {
    if (json == null) {
        return json;
    }
    return {
        
        'attackersScore': json['attackers_score'] == null ? undefined : json['attackers_score'],
        'campaignId': json['campaign_id'],
        'constellationId': json['constellation_id'],
        'defenderId': json['defender_id'] == null ? undefined : json['defender_id'],
        'defenderScore': json['defender_score'] == null ? undefined : json['defender_score'],
        'eventType': json['event_type'],
        'participants': json['participants'] == null ? undefined : ((json['participants'] as Array<any>).map(EsiSovereigntyCampaignsGetInnerParticipantsInnerFromJSON)),
        'solarSystemId': json['solar_system_id'],
        'startTime': (new Date(json['start_time'])),
        'structureId': json['structure_id'],
    };
}

export function EsiSovereigntyCampaignsGetInnerToJSON(json: any): EsiSovereigntyCampaignsGetInner {
    return EsiSovereigntyCampaignsGetInnerToJSONTyped(json, false);
}

export function EsiSovereigntyCampaignsGetInnerToJSONTyped(value?: EsiSovereigntyCampaignsGetInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attackers_score': value['attackersScore'],
        'campaign_id': value['campaignId'],
        'constellation_id': value['constellationId'],
        'defender_id': value['defenderId'],
        'defender_score': value['defenderScore'],
        'event_type': value['eventType'],
        'participants': value['participants'] == null ? undefined : ((value['participants'] as Array<any>).map(EsiSovereigntyCampaignsGetInnerParticipantsInnerToJSON)),
        'solar_system_id': value['solarSystemId'],
        'start_time': ((value['startTime']).toISOString()),
        'structure_id': value['structureId'],
    };
}

