/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stroopwafel Ingestion (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EsiSovereigntyStructuresGetInner
 */
export interface EsiSovereigntyStructuresGetInner {
    /**
     * The alliance that owns the structure.
     * 
     * @type {number}
     * @memberof EsiSovereigntyStructuresGetInner
     */
    allianceId: number;
    /**
     * Solar system in which the structure is located.
     * 
     * @type {number}
     * @memberof EsiSovereigntyStructuresGetInner
     */
    solarSystemId: number;
    /**
     * Unique item ID for this structure.
     * @type {number}
     * @memberof EsiSovereigntyStructuresGetInner
     */
    structureId: number;
    /**
     * A reference to the type of structure this is.
     * 
     * @type {number}
     * @memberof EsiSovereigntyStructuresGetInner
     */
    structureTypeId: number;
    /**
     * The occupancy level for the next or current vulnerability window. This takes into account all development indexes and capital system bonuses. Also known as Activity Defense Multiplier from in the client. It increases the time that attackers must spend using their entosis links on the structure.
     * 
     * @type {number}
     * @memberof EsiSovereigntyStructuresGetInner
     */
    vulnerabilityOccupancyLevel?: number;
    /**
     * The time at which the next or current vulnerability window ends. At the end of a vulnerability window the next window is recalculated and locked in along with the vulnerabilityOccupancyLevel. If the structure is not in 100% entosis control of the defender, it will go in to 'overtime' and stay vulnerable for as long as that situation persists. Only once the defenders have 100% entosis control and has the vulnerableEndTime passed does the vulnerability interval expire and a new one is calculated.
     * 
     * @type {Date}
     * @memberof EsiSovereigntyStructuresGetInner
     */
    vulnerableEndTime?: Date;
    /**
     * The next time at which the structure will become vulnerable. Or the start time of the current window if current time is between this and vulnerableEndTime.
     * 
     * @type {Date}
     * @memberof EsiSovereigntyStructuresGetInner
     */
    vulnerableStartTime?: Date;
}

/**
 * Check if a given object implements the EsiSovereigntyStructuresGetInner interface.
 */
export function instanceOfEsiSovereigntyStructuresGetInner(value: object): value is EsiSovereigntyStructuresGetInner {
    if (!('allianceId' in value) || value['allianceId'] === undefined) return false;
    if (!('solarSystemId' in value) || value['solarSystemId'] === undefined) return false;
    if (!('structureId' in value) || value['structureId'] === undefined) return false;
    if (!('structureTypeId' in value) || value['structureTypeId'] === undefined) return false;
    return true;
}

export function EsiSovereigntyStructuresGetInnerFromJSON(json: any): EsiSovereigntyStructuresGetInner {
    return EsiSovereigntyStructuresGetInnerFromJSONTyped(json, false);
}

export function EsiSovereigntyStructuresGetInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): EsiSovereigntyStructuresGetInner {
    if (json == null) {
        return json;
    }
    return {
        
        'allianceId': json['alliance_id'],
        'solarSystemId': json['solar_system_id'],
        'structureId': json['structure_id'],
        'structureTypeId': json['structure_type_id'],
        'vulnerabilityOccupancyLevel': json['vulnerability_occupancy_level'] == null ? undefined : json['vulnerability_occupancy_level'],
        'vulnerableEndTime': json['vulnerable_end_time'] == null ? undefined : (new Date(json['vulnerable_end_time'])),
        'vulnerableStartTime': json['vulnerable_start_time'] == null ? undefined : (new Date(json['vulnerable_start_time'])),
    };
}

export function EsiSovereigntyStructuresGetInnerToJSON(json: any): EsiSovereigntyStructuresGetInner {
    return EsiSovereigntyStructuresGetInnerToJSONTyped(json, false);
}

export function EsiSovereigntyStructuresGetInnerToJSONTyped(value?: EsiSovereigntyStructuresGetInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alliance_id': value['allianceId'],
        'solar_system_id': value['solarSystemId'],
        'structure_id': value['structureId'],
        'structure_type_id': value['structureTypeId'],
        'vulnerability_occupancy_level': value['vulnerabilityOccupancyLevel'],
        'vulnerable_end_time': value['vulnerableEndTime'] == null ? undefined : ((value['vulnerableEndTime']).toISOString()),
        'vulnerable_start_time': value['vulnerableStartTime'] == null ? undefined : ((value['vulnerableStartTime']).toISOString()),
    };
}

