/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stroopwafel Ingestion (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Coordinates of the structure in Cartesian space relative to the Sun, in metres.
 * 
 * @export
 * @interface EsiUniverseStructuresStructureIdGetPosition
 */
export interface EsiUniverseStructuresStructureIdGetPosition {
    /**
     * 
     * @type {number}
     * @memberof EsiUniverseStructuresStructureIdGetPosition
     */
    x: number;
    /**
     * 
     * @type {number}
     * @memberof EsiUniverseStructuresStructureIdGetPosition
     */
    y: number;
    /**
     * 
     * @type {number}
     * @memberof EsiUniverseStructuresStructureIdGetPosition
     */
    z: number;
}

/**
 * Check if a given object implements the EsiUniverseStructuresStructureIdGetPosition interface.
 */
export function instanceOfEsiUniverseStructuresStructureIdGetPosition(value: object): value is EsiUniverseStructuresStructureIdGetPosition {
    if (!('x' in value) || value['x'] === undefined) return false;
    if (!('y' in value) || value['y'] === undefined) return false;
    if (!('z' in value) || value['z'] === undefined) return false;
    return true;
}

export function EsiUniverseStructuresStructureIdGetPositionFromJSON(json: any): EsiUniverseStructuresStructureIdGetPosition {
    return EsiUniverseStructuresStructureIdGetPositionFromJSONTyped(json, false);
}

export function EsiUniverseStructuresStructureIdGetPositionFromJSONTyped(json: any, ignoreDiscriminator: boolean): EsiUniverseStructuresStructureIdGetPosition {
    if (json == null) {
        return json;
    }
    return {
        
        'x': json['x'],
        'y': json['y'],
        'z': json['z'],
    };
}

export function EsiUniverseStructuresStructureIdGetPositionToJSON(json: any): EsiUniverseStructuresStructureIdGetPosition {
    return EsiUniverseStructuresStructureIdGetPositionToJSONTyped(json, false);
}

export function EsiUniverseStructuresStructureIdGetPositionToJSONTyped(value?: EsiUniverseStructuresStructureIdGetPosition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'x': value['x'],
        'y': value['y'],
        'z': value['z'],
    };
}

