/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stroopwafel Ingestion (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EsiCharactersCharacterIdAssetsLocationsPostInnerPosition } from './EsiCharactersCharacterIdAssetsLocationsPostInnerPosition';
import {
    EsiCharactersCharacterIdAssetsLocationsPostInnerPositionFromJSON,
    EsiCharactersCharacterIdAssetsLocationsPostInnerPositionFromJSONTyped,
    EsiCharactersCharacterIdAssetsLocationsPostInnerPositionToJSON,
    EsiCharactersCharacterIdAssetsLocationsPostInnerPositionToJSONTyped,
} from './EsiCharactersCharacterIdAssetsLocationsPostInnerPosition';

/**
 * 
 * @export
 * @interface EsiUniverseStationsStationIdGet
 */
export interface EsiUniverseStationsStationIdGet {
    /**
     * 
     * @type {number}
     * @memberof EsiUniverseStationsStationIdGet
     */
    maxDockableShipVolume: number;
    /**
     * 
     * @type {string}
     * @memberof EsiUniverseStationsStationIdGet
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof EsiUniverseStationsStationIdGet
     */
    officeRentalCost: number;
    /**
     * ID of the corporation that controls this station
     * @type {number}
     * @memberof EsiUniverseStationsStationIdGet
     */
    owner?: number;
    /**
     * 
     * @type {EsiCharactersCharacterIdAssetsLocationsPostInnerPosition}
     * @memberof EsiUniverseStationsStationIdGet
     */
    position: EsiCharactersCharacterIdAssetsLocationsPostInnerPosition;
    /**
     * 
     * @type {number}
     * @memberof EsiUniverseStationsStationIdGet
     */
    raceId?: number;
    /**
     * 
     * @type {number}
     * @memberof EsiUniverseStationsStationIdGet
     */
    reprocessingEfficiency: number;
    /**
     * 
     * @type {number}
     * @memberof EsiUniverseStationsStationIdGet
     */
    reprocessingStationsTake: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof EsiUniverseStationsStationIdGet
     */
    services: Array<EsiUniverseStationsStationIdGetServicesEnum>;
    /**
     * 
     * @type {number}
     * @memberof EsiUniverseStationsStationIdGet
     */
    stationId: number;
    /**
     * The solar system this station is in
     * @type {number}
     * @memberof EsiUniverseStationsStationIdGet
     */
    systemId: number;
    /**
     * 
     * @type {number}
     * @memberof EsiUniverseStationsStationIdGet
     */
    typeId: number;
}


/**
 * @export
 */
export const EsiUniverseStationsStationIdGetServicesEnum = {
    BountyMissions: 'bounty-missions',
    AssasinationMissions: 'assasination-missions',
    CourierMissions: 'courier-missions',
    Interbus: 'interbus',
    ReprocessingPlant: 'reprocessing-plant',
    Refinery: 'refinery',
    Market: 'market',
    BlackMarket: 'black-market',
    StockExchange: 'stock-exchange',
    Cloning: 'cloning',
    Surgery: 'surgery',
    DnaTherapy: 'dna-therapy',
    RepairFacilities: 'repair-facilities',
    Factory: 'factory',
    Labratory: 'labratory',
    Gambling: 'gambling',
    Fitting: 'fitting',
    Paintshop: 'paintshop',
    News: 'news',
    Storage: 'storage',
    Insurance: 'insurance',
    Docking: 'docking',
    OfficeRental: 'office-rental',
    JumpCloneFacility: 'jump-clone-facility',
    LoyaltyPointStore: 'loyalty-point-store',
    NavyOffices: 'navy-offices',
    SecurityOffices: 'security-offices'
} as const;
export type EsiUniverseStationsStationIdGetServicesEnum = typeof EsiUniverseStationsStationIdGetServicesEnum[keyof typeof EsiUniverseStationsStationIdGetServicesEnum];


/**
 * Check if a given object implements the EsiUniverseStationsStationIdGet interface.
 */
export function instanceOfEsiUniverseStationsStationIdGet(value: object): value is EsiUniverseStationsStationIdGet {
    if (!('maxDockableShipVolume' in value) || value['maxDockableShipVolume'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('officeRentalCost' in value) || value['officeRentalCost'] === undefined) return false;
    if (!('position' in value) || value['position'] === undefined) return false;
    if (!('reprocessingEfficiency' in value) || value['reprocessingEfficiency'] === undefined) return false;
    if (!('reprocessingStationsTake' in value) || value['reprocessingStationsTake'] === undefined) return false;
    if (!('services' in value) || value['services'] === undefined) return false;
    if (!('stationId' in value) || value['stationId'] === undefined) return false;
    if (!('systemId' in value) || value['systemId'] === undefined) return false;
    if (!('typeId' in value) || value['typeId'] === undefined) return false;
    return true;
}

export function EsiUniverseStationsStationIdGetFromJSON(json: any): EsiUniverseStationsStationIdGet {
    return EsiUniverseStationsStationIdGetFromJSONTyped(json, false);
}

export function EsiUniverseStationsStationIdGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): EsiUniverseStationsStationIdGet {
    if (json == null) {
        return json;
    }
    return {
        
        'maxDockableShipVolume': json['max_dockable_ship_volume'],
        'name': json['name'],
        'officeRentalCost': json['office_rental_cost'],
        'owner': json['owner'] == null ? undefined : json['owner'],
        'position': EsiCharactersCharacterIdAssetsLocationsPostInnerPositionFromJSON(json['position']),
        'raceId': json['race_id'] == null ? undefined : json['race_id'],
        'reprocessingEfficiency': json['reprocessing_efficiency'],
        'reprocessingStationsTake': json['reprocessing_stations_take'],
        'services': json['services'],
        'stationId': json['station_id'],
        'systemId': json['system_id'],
        'typeId': json['type_id'],
    };
}

export function EsiUniverseStationsStationIdGetToJSON(json: any): EsiUniverseStationsStationIdGet {
    return EsiUniverseStationsStationIdGetToJSONTyped(json, false);
}

export function EsiUniverseStationsStationIdGetToJSONTyped(value?: EsiUniverseStationsStationIdGet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'max_dockable_ship_volume': value['maxDockableShipVolume'],
        'name': value['name'],
        'office_rental_cost': value['officeRentalCost'],
        'owner': value['owner'],
        'position': EsiCharactersCharacterIdAssetsLocationsPostInnerPositionToJSON(value['position']),
        'race_id': value['raceId'],
        'reprocessing_efficiency': value['reprocessingEfficiency'],
        'reprocessing_stations_take': value['reprocessingStationsTake'],
        'services': value['services'],
        'station_id': value['stationId'],
        'system_id': value['systemId'],
        'type_id': value['typeId'],
    };
}

