/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stroopwafel Ingestion (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EsiUniverseStructuresStructureIdGetPosition } from './EsiUniverseStructuresStructureIdGetPosition';
import {
    EsiUniverseStructuresStructureIdGetPositionFromJSON,
    EsiUniverseStructuresStructureIdGetPositionFromJSONTyped,
    EsiUniverseStructuresStructureIdGetPositionToJSON,
    EsiUniverseStructuresStructureIdGetPositionToJSONTyped,
} from './EsiUniverseStructuresStructureIdGetPosition';

/**
 * 
 * @export
 * @interface EsiUniverseStructuresStructureIdGet
 */
export interface EsiUniverseStructuresStructureIdGet {
    /**
     * The full name of the structure
     * @type {string}
     * @memberof EsiUniverseStructuresStructureIdGet
     */
    name: string;
    /**
     * The ID of the corporation who owns this particular structure
     * @type {number}
     * @memberof EsiUniverseStructuresStructureIdGet
     */
    ownerId: number;
    /**
     * 
     * @type {EsiUniverseStructuresStructureIdGetPosition}
     * @memberof EsiUniverseStructuresStructureIdGet
     */
    position?: EsiUniverseStructuresStructureIdGetPosition;
    /**
     * 
     * @type {number}
     * @memberof EsiUniverseStructuresStructureIdGet
     */
    solarSystemId: number;
    /**
     * 
     * @type {number}
     * @memberof EsiUniverseStructuresStructureIdGet
     */
    typeId?: number;
}

/**
 * Check if a given object implements the EsiUniverseStructuresStructureIdGet interface.
 */
export function instanceOfEsiUniverseStructuresStructureIdGet(value: object): value is EsiUniverseStructuresStructureIdGet {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('ownerId' in value) || value['ownerId'] === undefined) return false;
    if (!('solarSystemId' in value) || value['solarSystemId'] === undefined) return false;
    return true;
}

export function EsiUniverseStructuresStructureIdGetFromJSON(json: any): EsiUniverseStructuresStructureIdGet {
    return EsiUniverseStructuresStructureIdGetFromJSONTyped(json, false);
}

export function EsiUniverseStructuresStructureIdGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): EsiUniverseStructuresStructureIdGet {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'ownerId': json['owner_id'],
        'position': json['position'] == null ? undefined : EsiUniverseStructuresStructureIdGetPositionFromJSON(json['position']),
        'solarSystemId': json['solar_system_id'],
        'typeId': json['type_id'] == null ? undefined : json['type_id'],
    };
}

export function EsiUniverseStructuresStructureIdGetToJSON(json: any): EsiUniverseStructuresStructureIdGet {
    return EsiUniverseStructuresStructureIdGetToJSONTyped(json, false);
}

export function EsiUniverseStructuresStructureIdGetToJSONTyped(value?: EsiUniverseStructuresStructureIdGet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'owner_id': value['ownerId'],
        'position': EsiUniverseStructuresStructureIdGetPositionToJSON(value['position']),
        'solar_system_id': value['solarSystemId'],
        'type_id': value['typeId'],
    };
}

