/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stroopwafel Ingestion (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EsiWarsWarIdGetAlliesInner } from './EsiWarsWarIdGetAlliesInner';
import {
    EsiWarsWarIdGetAlliesInnerFromJSON,
    EsiWarsWarIdGetAlliesInnerFromJSONTyped,
    EsiWarsWarIdGetAlliesInnerToJSON,
    EsiWarsWarIdGetAlliesInnerToJSONTyped,
} from './EsiWarsWarIdGetAlliesInner';
import type { EsiWarsWarIdGetDefender } from './EsiWarsWarIdGetDefender';
import {
    EsiWarsWarIdGetDefenderFromJSON,
    EsiWarsWarIdGetDefenderFromJSONTyped,
    EsiWarsWarIdGetDefenderToJSON,
    EsiWarsWarIdGetDefenderToJSONTyped,
} from './EsiWarsWarIdGetDefender';
import type { EsiWarsWarIdGetAggressor } from './EsiWarsWarIdGetAggressor';
import {
    EsiWarsWarIdGetAggressorFromJSON,
    EsiWarsWarIdGetAggressorFromJSONTyped,
    EsiWarsWarIdGetAggressorToJSON,
    EsiWarsWarIdGetAggressorToJSONTyped,
} from './EsiWarsWarIdGetAggressor';

/**
 * 
 * @export
 * @interface EsiWarsWarIdGet
 */
export interface EsiWarsWarIdGet {
    /**
     * 
     * @type {EsiWarsWarIdGetAggressor}
     * @memberof EsiWarsWarIdGet
     */
    aggressor: EsiWarsWarIdGetAggressor;
    /**
     * allied corporations or alliances, each object contains either corporation_id or alliance_id
     * @type {Array<EsiWarsWarIdGetAlliesInner>}
     * @memberof EsiWarsWarIdGet
     */
    allies?: Array<EsiWarsWarIdGetAlliesInner>;
    /**
     * Time that the war was declared
     * @type {Date}
     * @memberof EsiWarsWarIdGet
     */
    declared: Date;
    /**
     * 
     * @type {EsiWarsWarIdGetDefender}
     * @memberof EsiWarsWarIdGet
     */
    defender: EsiWarsWarIdGetDefender;
    /**
     * Time the war ended and shooting was no longer allowed
     * @type {Date}
     * @memberof EsiWarsWarIdGet
     */
    finished?: Date;
    /**
     * ID of the specified war
     * @type {number}
     * @memberof EsiWarsWarIdGet
     */
    id: number;
    /**
     * Was the war declared mutual by both parties
     * @type {boolean}
     * @memberof EsiWarsWarIdGet
     */
    mutual: boolean;
    /**
     * Is the war currently open for allies or not
     * @type {boolean}
     * @memberof EsiWarsWarIdGet
     */
    openForAllies: boolean;
    /**
     * Time the war was retracted but both sides could still shoot each other
     * @type {Date}
     * @memberof EsiWarsWarIdGet
     */
    retracted?: Date;
    /**
     * Time when the war started and both sides could shoot each other
     * @type {Date}
     * @memberof EsiWarsWarIdGet
     */
    started?: Date;
}

/**
 * Check if a given object implements the EsiWarsWarIdGet interface.
 */
export function instanceOfEsiWarsWarIdGet(value: object): value is EsiWarsWarIdGet {
    if (!('aggressor' in value) || value['aggressor'] === undefined) return false;
    if (!('declared' in value) || value['declared'] === undefined) return false;
    if (!('defender' in value) || value['defender'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('mutual' in value) || value['mutual'] === undefined) return false;
    if (!('openForAllies' in value) || value['openForAllies'] === undefined) return false;
    return true;
}

export function EsiWarsWarIdGetFromJSON(json: any): EsiWarsWarIdGet {
    return EsiWarsWarIdGetFromJSONTyped(json, false);
}

export function EsiWarsWarIdGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): EsiWarsWarIdGet {
    if (json == null) {
        return json;
    }
    return {
        
        'aggressor': EsiWarsWarIdGetAggressorFromJSON(json['aggressor']),
        'allies': json['allies'] == null ? undefined : ((json['allies'] as Array<any>).map(EsiWarsWarIdGetAlliesInnerFromJSON)),
        'declared': (new Date(json['declared'])),
        'defender': EsiWarsWarIdGetDefenderFromJSON(json['defender']),
        'finished': json['finished'] == null ? undefined : (new Date(json['finished'])),
        'id': json['id'],
        'mutual': json['mutual'],
        'openForAllies': json['open_for_allies'],
        'retracted': json['retracted'] == null ? undefined : (new Date(json['retracted'])),
        'started': json['started'] == null ? undefined : (new Date(json['started'])),
    };
}

export function EsiWarsWarIdGetToJSON(json: any): EsiWarsWarIdGet {
    return EsiWarsWarIdGetToJSONTyped(json, false);
}

export function EsiWarsWarIdGetToJSONTyped(value?: EsiWarsWarIdGet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aggressor': EsiWarsWarIdGetAggressorToJSON(value['aggressor']),
        'allies': value['allies'] == null ? undefined : ((value['allies'] as Array<any>).map(EsiWarsWarIdGetAlliesInnerToJSON)),
        'declared': ((value['declared']).toISOString()),
        'defender': EsiWarsWarIdGetDefenderToJSON(value['defender']),
        'finished': value['finished'] == null ? undefined : ((value['finished']).toISOString()),
        'id': value['id'],
        'mutual': value['mutual'],
        'open_for_allies': value['openForAllies'],
        'retracted': value['retracted'] == null ? undefined : ((value['retracted']).toISOString()),
        'started': value['started'] == null ? undefined : ((value['started']).toISOString()),
    };
}

