/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FleetsFleetIdWingsGetInnerSquadsInner } from './FleetsFleetIdWingsGetInnerSquadsInner';
import {
    FleetsFleetIdWingsGetInnerSquadsInnerFromJSON,
    FleetsFleetIdWingsGetInnerSquadsInnerFromJSONTyped,
    FleetsFleetIdWingsGetInnerSquadsInnerToJSON,
    FleetsFleetIdWingsGetInnerSquadsInnerToJSONTyped,
} from './FleetsFleetIdWingsGetInnerSquadsInner';

/**
 * 
 * @export
 * @interface FleetsFleetIdWingsGetInner
 */
export interface FleetsFleetIdWingsGetInner {
    /**
     * 
     * @type {number}
     * @memberof FleetsFleetIdWingsGetInner
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof FleetsFleetIdWingsGetInner
     */
    name: string;
    /**
     * 
     * @type {Array<FleetsFleetIdWingsGetInnerSquadsInner>}
     * @memberof FleetsFleetIdWingsGetInner
     */
    squads: Array<FleetsFleetIdWingsGetInnerSquadsInner>;
}

/**
 * Check if a given object implements the FleetsFleetIdWingsGetInner interface.
 */
export function instanceOfFleetsFleetIdWingsGetInner(value: object): value is FleetsFleetIdWingsGetInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('squads' in value) || value['squads'] === undefined) return false;
    return true;
}

export function FleetsFleetIdWingsGetInnerFromJSON(json: any): FleetsFleetIdWingsGetInner {
    return FleetsFleetIdWingsGetInnerFromJSONTyped(json, false);
}

export function FleetsFleetIdWingsGetInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): FleetsFleetIdWingsGetInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'squads': ((json['squads'] as Array<any>).map(FleetsFleetIdWingsGetInnerSquadsInnerFromJSON)),
    };
}

export function FleetsFleetIdWingsGetInnerToJSON(json: any): FleetsFleetIdWingsGetInner {
    return FleetsFleetIdWingsGetInnerToJSONTyped(json, false);
}

export function FleetsFleetIdWingsGetInnerToJSONTyped(value?: FleetsFleetIdWingsGetInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'squads': ((value['squads'] as Array<any>).map(FleetsFleetIdWingsGetInnerSquadsInnerToJSON)),
    };
}

