/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FreelanceJobsDetailBroadcastlocations } from './FreelanceJobsDetailBroadcastlocations';
import {
    FreelanceJobsDetailBroadcastlocationsFromJSON,
    FreelanceJobsDetailBroadcastlocationsFromJSONTyped,
    FreelanceJobsDetailBroadcastlocationsToJSON,
    FreelanceJobsDetailBroadcastlocationsToJSONTyped,
} from './FreelanceJobsDetailBroadcastlocations';
import type { FreelanceJobsDetailRestrictions } from './FreelanceJobsDetailRestrictions';
import {
    FreelanceJobsDetailRestrictionsFromJSON,
    FreelanceJobsDetailRestrictionsFromJSONTyped,
    FreelanceJobsDetailRestrictionsToJSON,
    FreelanceJobsDetailRestrictionsToJSONTyped,
} from './FreelanceJobsDetailRestrictions';

/**
 * 
 * @export
 * @interface FreelanceJobsDetailAccessandvisibility
 */
export interface FreelanceJobsDetailAccessandvisibility {
    /**
     * Whether the job is protected by an ACL
     * @type {boolean}
     * @memberof FreelanceJobsDetailAccessandvisibility
     */
    aclProtected: boolean;
    /**
     * Solar systems where the job is broadcast
     * @type {Array<FreelanceJobsDetailBroadcastlocations>}
     * @memberof FreelanceJobsDetailAccessandvisibility
     */
    broadcastLocations?: Array<FreelanceJobsDetailBroadcastlocations>;
    /**
     * Restrictions on who can participate
     * @type {FreelanceJobsDetailRestrictions}
     * @memberof FreelanceJobsDetailAccessandvisibility
     */
    restrictions?: FreelanceJobsDetailRestrictions;
}

/**
 * Check if a given object implements the FreelanceJobsDetailAccessandvisibility interface.
 */
export function instanceOfFreelanceJobsDetailAccessandvisibility(value: object): value is FreelanceJobsDetailAccessandvisibility {
    if (!('aclProtected' in value) || value['aclProtected'] === undefined) return false;
    return true;
}

export function FreelanceJobsDetailAccessandvisibilityFromJSON(json: any): FreelanceJobsDetailAccessandvisibility {
    return FreelanceJobsDetailAccessandvisibilityFromJSONTyped(json, false);
}

export function FreelanceJobsDetailAccessandvisibilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): FreelanceJobsDetailAccessandvisibility {
    if (json == null) {
        return json;
    }
    return {
        
        'aclProtected': json['acl_protected'],
        'broadcastLocations': json['broadcast_locations'] == null ? undefined : ((json['broadcast_locations'] as Array<any>).map(FreelanceJobsDetailBroadcastlocationsFromJSON)),
        'restrictions': json['restrictions'] == null ? undefined : FreelanceJobsDetailRestrictionsFromJSON(json['restrictions']),
    };
}

export function FreelanceJobsDetailAccessandvisibilityToJSON(json: any): FreelanceJobsDetailAccessandvisibility {
    return FreelanceJobsDetailAccessandvisibilityToJSONTyped(json, false);
}

export function FreelanceJobsDetailAccessandvisibilityToJSONTyped(value?: FreelanceJobsDetailAccessandvisibility | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'acl_protected': value['aclProtected'],
        'broadcast_locations': value['broadcastLocations'] == null ? undefined : ((value['broadcastLocations'] as Array<any>).map(FreelanceJobsDetailBroadcastlocationsToJSON)),
        'restrictions': FreelanceJobsDetailRestrictionsToJSON(value['restrictions']),
    };
}

