/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FreelanceJobsDetailCreatorcorporation
 */
export interface FreelanceJobsDetailCreatorcorporation {
    /**
     * 
     * @type {number}
     * @memberof FreelanceJobsDetailCreatorcorporation
     */
    id: number;
    /**
     * Corporation name
     * @type {string}
     * @memberof FreelanceJobsDetailCreatorcorporation
     */
    name: string;
}

/**
 * Check if a given object implements the FreelanceJobsDetailCreatorcorporation interface.
 */
export function instanceOfFreelanceJobsDetailCreatorcorporation(value: object): value is FreelanceJobsDetailCreatorcorporation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function FreelanceJobsDetailCreatorcorporationFromJSON(json: any): FreelanceJobsDetailCreatorcorporation {
    return FreelanceJobsDetailCreatorcorporationFromJSONTyped(json, false);
}

export function FreelanceJobsDetailCreatorcorporationFromJSONTyped(json: any, ignoreDiscriminator: boolean): FreelanceJobsDetailCreatorcorporation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function FreelanceJobsDetailCreatorcorporationToJSON(json: any): FreelanceJobsDetailCreatorcorporation {
    return FreelanceJobsDetailCreatorcorporationToJSONTyped(json, false);
}

export function FreelanceJobsDetailCreatorcorporationToJSONTyped(value?: FreelanceJobsDetailCreatorcorporation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

