/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CorporationItemDelivery } from './CorporationItemDelivery';
import {
    instanceOfCorporationItemDelivery,
    CorporationItemDeliveryFromJSON,
    CorporationItemDeliveryFromJSONTyped,
    CorporationItemDeliveryToJSON,
} from './CorporationItemDelivery';
import type { Matcher } from './Matcher';
import {
    instanceOfMatcher,
    MatcherFromJSON,
    MatcherFromJSONTyped,
    MatcherToJSON,
} from './Matcher';
import type { Options } from './Options';
import {
    instanceOfOptions,
    OptionsFromJSON,
    OptionsFromJSONTyped,
    OptionsToJSON,
} from './Options';

/**
 * @type FreelanceJobsDetailConfigurationParametersValue
 * 
 * @export
 */
export type FreelanceJobsDetailConfigurationParametersValue = CorporationItemDelivery | Matcher | ModelBoolean | Options;

export function FreelanceJobsDetailConfigurationParametersValueFromJSON(json: any): FreelanceJobsDetailConfigurationParametersValue {
    return FreelanceJobsDetailConfigurationParametersValueFromJSONTyped(json, false);
}

export function FreelanceJobsDetailConfigurationParametersValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): FreelanceJobsDetailConfigurationParametersValue {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfCorporationItemDelivery(json)) {
        return CorporationItemDeliveryFromJSONTyped(json, true);
    }
    if (instanceOfMatcher(json)) {
        return MatcherFromJSONTyped(json, true);
    }
    if (instanceOfOptions(json)) {
        return OptionsFromJSONTyped(json, true);
    }
    if (instanceOfboolean(json)) {
        return booleanFromJSONTyped(json, true);
    }

    return {} as any;
}

export function FreelanceJobsDetailConfigurationParametersValueToJSON(json: any): any {
    return FreelanceJobsDetailConfigurationParametersValueToJSONTyped(json, false);
}

export function FreelanceJobsDetailConfigurationParametersValueToJSONTyped(value?: FreelanceJobsDetailConfigurationParametersValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfCorporationItemDelivery(value)) {
        return CorporationItemDeliveryToJSON(value as CorporationItemDelivery);
    }
    if (instanceOfMatcher(value)) {
        return MatcherToJSON(value as Matcher);
    }
    if (instanceOfOptions(value)) {
        return OptionsToJSON(value as Options);
    }
    if (instanceOfboolean(value)) {
        return booleanToJSON(value as boolean);
    }

    return {};
}

