/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FwLeaderboardsCharactersGetVictoryPoints } from './FwLeaderboardsCharactersGetVictoryPoints';
import {
    FwLeaderboardsCharactersGetVictoryPointsFromJSON,
    FwLeaderboardsCharactersGetVictoryPointsFromJSONTyped,
    FwLeaderboardsCharactersGetVictoryPointsToJSON,
    FwLeaderboardsCharactersGetVictoryPointsToJSONTyped,
} from './FwLeaderboardsCharactersGetVictoryPoints';
import type { FwLeaderboardsCharactersGetKills } from './FwLeaderboardsCharactersGetKills';
import {
    FwLeaderboardsCharactersGetKillsFromJSON,
    FwLeaderboardsCharactersGetKillsFromJSONTyped,
    FwLeaderboardsCharactersGetKillsToJSON,
    FwLeaderboardsCharactersGetKillsToJSONTyped,
} from './FwLeaderboardsCharactersGetKills';

/**
 * 
 * @export
 * @interface FwLeaderboardsCharactersGet
 */
export interface FwLeaderboardsCharactersGet {
    /**
     * 
     * @type {FwLeaderboardsCharactersGetKills}
     * @memberof FwLeaderboardsCharactersGet
     */
    kills: FwLeaderboardsCharactersGetKills;
    /**
     * 
     * @type {FwLeaderboardsCharactersGetVictoryPoints}
     * @memberof FwLeaderboardsCharactersGet
     */
    victoryPoints: FwLeaderboardsCharactersGetVictoryPoints;
}

/**
 * Check if a given object implements the FwLeaderboardsCharactersGet interface.
 */
export function instanceOfFwLeaderboardsCharactersGet(value: object): value is FwLeaderboardsCharactersGet {
    if (!('kills' in value) || value['kills'] === undefined) return false;
    if (!('victoryPoints' in value) || value['victoryPoints'] === undefined) return false;
    return true;
}

export function FwLeaderboardsCharactersGetFromJSON(json: any): FwLeaderboardsCharactersGet {
    return FwLeaderboardsCharactersGetFromJSONTyped(json, false);
}

export function FwLeaderboardsCharactersGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): FwLeaderboardsCharactersGet {
    if (json == null) {
        return json;
    }
    return {
        
        'kills': FwLeaderboardsCharactersGetKillsFromJSON(json['kills']),
        'victoryPoints': FwLeaderboardsCharactersGetVictoryPointsFromJSON(json['victory_points']),
    };
}

export function FwLeaderboardsCharactersGetToJSON(json: any): FwLeaderboardsCharactersGet {
    return FwLeaderboardsCharactersGetToJSONTyped(json, false);
}

export function FwLeaderboardsCharactersGetToJSONTyped(value?: FwLeaderboardsCharactersGet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kills': FwLeaderboardsCharactersGetKillsToJSON(value['kills']),
        'victory_points': FwLeaderboardsCharactersGetVictoryPointsToJSON(value['victoryPoints']),
    };
}

