/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 200 ok object
 * @export
 * @interface GetAlliancesAllianceIdIconsOk
 */
export interface GetAlliancesAllianceIdIconsOk {
    /**
     * px128x128 string
     * @type {string}
     * @memberof GetAlliancesAllianceIdIconsOk
     */
    px128x128?: string;
    /**
     * px64x64 string
     * @type {string}
     * @memberof GetAlliancesAllianceIdIconsOk
     */
    px64x64?: string;
}

/**
 * Check if a given object implements the GetAlliancesAllianceIdIconsOk interface.
 */
export function instanceOfGetAlliancesAllianceIdIconsOk(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetAlliancesAllianceIdIconsOkFromJSON(json: any): GetAlliancesAllianceIdIconsOk {
    return GetAlliancesAllianceIdIconsOkFromJSONTyped(json, false);
}

export function GetAlliancesAllianceIdIconsOkFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAlliancesAllianceIdIconsOk {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'px128x128': !exists(json, 'px128x128') ? undefined : json['px128x128'],
        'px64x64': !exists(json, 'px64x64') ? undefined : json['px64x64'],
    };
}

export function GetAlliancesAllianceIdIconsOkToJSON(value?: GetAlliancesAllianceIdIconsOk | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'px128x128': value.px128x128,
        'px64x64': value.px64x64,
    };
}

