/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 200 ok object
 * @export
 * @interface GetCorporationsCorporationIdMedalsIssued200Ok
 */
export interface GetCorporationsCorporationIdMedalsIssued200Ok {
    /**
     * ID of the character who was rewarded this medal
     * @type {number}
     * @memberof GetCorporationsCorporationIdMedalsIssued200Ok
     */
    characterId: number;
    /**
     * issued_at string
     * @type {Date}
     * @memberof GetCorporationsCorporationIdMedalsIssued200Ok
     */
    issuedAt: Date;
    /**
     * ID of the character who issued the medal
     * @type {number}
     * @memberof GetCorporationsCorporationIdMedalsIssued200Ok
     */
    issuerId: number;
    /**
     * medal_id integer
     * @type {number}
     * @memberof GetCorporationsCorporationIdMedalsIssued200Ok
     */
    medalId: number;
    /**
     * reason string
     * @type {string}
     * @memberof GetCorporationsCorporationIdMedalsIssued200Ok
     */
    reason: string;
    /**
     * status string
     * @type {string}
     * @memberof GetCorporationsCorporationIdMedalsIssued200Ok
     */
    status: GetCorporationsCorporationIdMedalsIssued200OkStatusEnum;
}


/**
 * @export
 */
export const GetCorporationsCorporationIdMedalsIssued200OkStatusEnum = {
    Private: 'private',
    Public: 'public'
} as const;
export type GetCorporationsCorporationIdMedalsIssued200OkStatusEnum = typeof GetCorporationsCorporationIdMedalsIssued200OkStatusEnum[keyof typeof GetCorporationsCorporationIdMedalsIssued200OkStatusEnum];


/**
 * Check if a given object implements the GetCorporationsCorporationIdMedalsIssued200Ok interface.
 */
export function instanceOfGetCorporationsCorporationIdMedalsIssued200Ok(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "characterId" in value;
    isInstance = isInstance && "issuedAt" in value;
    isInstance = isInstance && "issuerId" in value;
    isInstance = isInstance && "medalId" in value;
    isInstance = isInstance && "reason" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function GetCorporationsCorporationIdMedalsIssued200OkFromJSON(json: any): GetCorporationsCorporationIdMedalsIssued200Ok {
    return GetCorporationsCorporationIdMedalsIssued200OkFromJSONTyped(json, false);
}

export function GetCorporationsCorporationIdMedalsIssued200OkFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCorporationsCorporationIdMedalsIssued200Ok {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'characterId': json['character_id'],
        'issuedAt': (new Date(json['issued_at'])),
        'issuerId': json['issuer_id'],
        'medalId': json['medal_id'],
        'reason': json['reason'],
        'status': json['status'],
    };
}

export function GetCorporationsCorporationIdMedalsIssued200OkToJSON(value?: GetCorporationsCorporationIdMedalsIssued200Ok | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'character_id': value.characterId,
        'issued_at': (value.issuedAt.toISOString()),
        'issuer_id': value.issuerId,
        'medal_id': value.medalId,
        'reason': value.reason,
        'status': value.status,
    };
}

