/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * last_week object
 * @export
 * @interface GetFwLeaderboardsCorporationsLastWeekLastWeek
 */
export interface GetFwLeaderboardsCorporationsLastWeekLastWeek {
    /**
     * Amount of kills
     * @type {number}
     * @memberof GetFwLeaderboardsCorporationsLastWeekLastWeek
     */
    amount?: number;
    /**
     * corporation_id integer
     * @type {number}
     * @memberof GetFwLeaderboardsCorporationsLastWeekLastWeek
     */
    corporationId?: number;
}

/**
 * Check if a given object implements the GetFwLeaderboardsCorporationsLastWeekLastWeek interface.
 */
export function instanceOfGetFwLeaderboardsCorporationsLastWeekLastWeek(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetFwLeaderboardsCorporationsLastWeekLastWeekFromJSON(json: any): GetFwLeaderboardsCorporationsLastWeekLastWeek {
    return GetFwLeaderboardsCorporationsLastWeekLastWeekFromJSONTyped(json, false);
}

export function GetFwLeaderboardsCorporationsLastWeekLastWeekFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFwLeaderboardsCorporationsLastWeekLastWeek {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'corporationId': !exists(json, 'corporation_id') ? undefined : json['corporation_id'],
    };
}

export function GetFwLeaderboardsCorporationsLastWeekLastWeekToJSON(value?: GetFwLeaderboardsCorporationsLastWeekLastWeek | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'corporation_id': value.corporationId,
    };
}

