/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 200 ok object
 * @export
 * @interface GetMarketsGroupsMarketGroupIdOk
 */
export interface GetMarketsGroupsMarketGroupIdOk {
    /**
     * description string
     * @type {string}
     * @memberof GetMarketsGroupsMarketGroupIdOk
     */
    description: string;
    /**
     * market_group_id integer
     * @type {number}
     * @memberof GetMarketsGroupsMarketGroupIdOk
     */
    marketGroupId: number;
    /**
     * name string
     * @type {string}
     * @memberof GetMarketsGroupsMarketGroupIdOk
     */
    name: string;
    /**
     * parent_group_id integer
     * @type {number}
     * @memberof GetMarketsGroupsMarketGroupIdOk
     */
    parentGroupId?: number;
    /**
     * types array
     * @type {Array<number>}
     * @memberof GetMarketsGroupsMarketGroupIdOk
     */
    types: Array<number>;
}

/**
 * Check if a given object implements the GetMarketsGroupsMarketGroupIdOk interface.
 */
export function instanceOfGetMarketsGroupsMarketGroupIdOk(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "marketGroupId" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "types" in value;

    return isInstance;
}

export function GetMarketsGroupsMarketGroupIdOkFromJSON(json: any): GetMarketsGroupsMarketGroupIdOk {
    return GetMarketsGroupsMarketGroupIdOkFromJSONTyped(json, false);
}

export function GetMarketsGroupsMarketGroupIdOkFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMarketsGroupsMarketGroupIdOk {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': json['description'],
        'marketGroupId': json['market_group_id'],
        'name': json['name'],
        'parentGroupId': !exists(json, 'parent_group_id') ? undefined : json['parent_group_id'],
        'types': json['types'],
    };
}

export function GetMarketsGroupsMarketGroupIdOkToJSON(value?: GetMarketsGroupsMarketGroupIdOk | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'market_group_id': value.marketGroupId,
        'name': value.name,
        'parent_group_id': value.parentGroupId,
        'types': value.types,
    };
}

