/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Not found
 * @export
 * @interface GetUniverseStructuresStructureIdNotFound
 */
export interface GetUniverseStructuresStructureIdNotFound {
    /**
     * Not found message
     * @type {string}
     * @memberof GetUniverseStructuresStructureIdNotFound
     */
    error?: string;
}

/**
 * Check if a given object implements the GetUniverseStructuresStructureIdNotFound interface.
 */
export function instanceOfGetUniverseStructuresStructureIdNotFound(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetUniverseStructuresStructureIdNotFoundFromJSON(json: any): GetUniverseStructuresStructureIdNotFound {
    return GetUniverseStructuresStructureIdNotFoundFromJSONTyped(json, false);
}

export function GetUniverseStructuresStructureIdNotFoundFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUniverseStructuresStructureIdNotFound {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : json['error'],
    };
}

export function GetUniverseStructuresStructureIdNotFoundToJSON(value?: GetUniverseStructuresStructureIdNotFound | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': value.error,
    };
}

