/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 200 ok object
 * @export
 * @interface GetUniverseSystemJumps200Ok
 */
export interface GetUniverseSystemJumps200Ok {
    /**
     * ship_jumps integer
     * @type {number}
     * @memberof GetUniverseSystemJumps200Ok
     */
    shipJumps: number;
    /**
     * system_id integer
     * @type {number}
     * @memberof GetUniverseSystemJumps200Ok
     */
    systemId: number;
}

/**
 * Check if a given object implements the GetUniverseSystemJumps200Ok interface.
 */
export function instanceOfGetUniverseSystemJumps200Ok(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "shipJumps" in value;
    isInstance = isInstance && "systemId" in value;

    return isInstance;
}

export function GetUniverseSystemJumps200OkFromJSON(json: any): GetUniverseSystemJumps200Ok {
    return GetUniverseSystemJumps200OkFromJSONTyped(json, false);
}

export function GetUniverseSystemJumps200OkFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUniverseSystemJumps200Ok {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'shipJumps': json['ship_jumps'],
        'systemId': json['system_id'],
    };
}

export function GetUniverseSystemJumps200OkToJSON(value?: GetUniverseSystemJumps200Ok | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ship_jumps': value.shipJumps,
        'system_id': value.systemId,
    };
}

