/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IncursionsGetInner
 */
export interface IncursionsGetInner {
    /**
     * The constellation id in which this incursion takes place
     * @type {number}
     * @memberof IncursionsGetInner
     */
    constellationId: number;
    /**
     * The attacking faction's id
     * @type {number}
     * @memberof IncursionsGetInner
     */
    factionId: number;
    /**
     * Whether the final encounter has boss or not
     * @type {boolean}
     * @memberof IncursionsGetInner
     */
    hasBoss: boolean;
    /**
     * A list of infested solar system ids that are a part of this incursion
     * @type {Array<number>}
     * @memberof IncursionsGetInner
     */
    infestedSolarSystems: Array<number>;
    /**
     * Influence of this incursion as a float from 0 to 1
     * @type {number}
     * @memberof IncursionsGetInner
     */
    influence: number;
    /**
     * Staging solar system for this incursion
     * @type {number}
     * @memberof IncursionsGetInner
     */
    stagingSolarSystemId: number;
    /**
     * The state of this incursion
     * @type {string}
     * @memberof IncursionsGetInner
     */
    state: IncursionsGetInnerStateEnum;
    /**
     * The type of this incursion
     * @type {string}
     * @memberof IncursionsGetInner
     */
    type: string;
}


/**
 * @export
 */
export const IncursionsGetInnerStateEnum = {
    Withdrawing: 'withdrawing',
    Mobilizing: 'mobilizing',
    Established: 'established'
} as const;
export type IncursionsGetInnerStateEnum = typeof IncursionsGetInnerStateEnum[keyof typeof IncursionsGetInnerStateEnum];


/**
 * Check if a given object implements the IncursionsGetInner interface.
 */
export function instanceOfIncursionsGetInner(value: object): value is IncursionsGetInner {
    if (!('constellationId' in value) || value['constellationId'] === undefined) return false;
    if (!('factionId' in value) || value['factionId'] === undefined) return false;
    if (!('hasBoss' in value) || value['hasBoss'] === undefined) return false;
    if (!('infestedSolarSystems' in value) || value['infestedSolarSystems'] === undefined) return false;
    if (!('influence' in value) || value['influence'] === undefined) return false;
    if (!('stagingSolarSystemId' in value) || value['stagingSolarSystemId'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function IncursionsGetInnerFromJSON(json: any): IncursionsGetInner {
    return IncursionsGetInnerFromJSONTyped(json, false);
}

export function IncursionsGetInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncursionsGetInner {
    if (json == null) {
        return json;
    }
    return {
        
        'constellationId': json['constellation_id'],
        'factionId': json['faction_id'],
        'hasBoss': json['has_boss'],
        'infestedSolarSystems': json['infested_solar_systems'],
        'influence': json['influence'],
        'stagingSolarSystemId': json['staging_solar_system_id'],
        'state': json['state'],
        'type': json['type'],
    };
}

export function IncursionsGetInnerToJSON(json: any): IncursionsGetInner {
    return IncursionsGetInnerToJSONTyped(json, false);
}

export function IncursionsGetInnerToJSONTyped(value?: IncursionsGetInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'constellation_id': value['constellationId'],
        'faction_id': value['factionId'],
        'has_boss': value['hasBoss'],
        'infested_solar_systems': value['infestedSolarSystems'],
        'influence': value['influence'],
        'staging_solar_system_id': value['stagingSolarSystemId'],
        'state': value['state'],
        'type': value['type'],
    };
}

