/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Manual
 */
export interface Manual {
    /**
     * 
     * @type {object}
     * @memberof Manual
     */
    manual?: object;
}

/**
 * Check if a given object implements the Manual interface.
 */
export function instanceOfManual(value: object): value is Manual {
    return true;
}

export function ManualFromJSON(json: any): Manual {
    return ManualFromJSONTyped(json, false);
}

export function ManualFromJSONTyped(json: any, ignoreDiscriminator: boolean): Manual {
    if (json == null) {
        return json;
    }
    return {
        
        'manual': json['manual'] == null ? undefined : json['manual'],
    };
}

export function ManualToJSON(json: any): Manual {
    return ManualToJSONTyped(json, false);
}

export function ManualToJSONTyped(value?: Manual | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'manual': value['manual'],
    };
}

