/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FreelanceJobsDetailParameterboolean } from './FreelanceJobsDetailParameterboolean';
import {
    FreelanceJobsDetailParameterbooleanFromJSON,
    FreelanceJobsDetailParameterbooleanFromJSONTyped,
    FreelanceJobsDetailParameterbooleanToJSON,
    FreelanceJobsDetailParameterbooleanToJSONTyped,
} from './FreelanceJobsDetailParameterboolean';

/**
 * 
 * @export
 * @interface ModelBoolean
 */
export interface ModelBoolean {
    /**
     * Parameter that can be toggled
     * @type {FreelanceJobsDetailParameterboolean}
     * @memberof ModelBoolean
     */
    _boolean?: FreelanceJobsDetailParameterboolean;
}

/**
 * Check if a given object implements the ModelBoolean interface.
 */
export function instanceOfModelBoolean(value: object): value is ModelBoolean {
    return true;
}

export function ModelBooleanFromJSON(json: any): ModelBoolean {
    return ModelBooleanFromJSONTyped(json, false);
}

export function ModelBooleanFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelBoolean {
    if (json == null) {
        return json;
    }
    return {
        
        '_boolean': json['boolean'] == null ? undefined : FreelanceJobsDetailParameterbooleanFromJSON(json['boolean']),
    };
}

export function ModelBooleanToJSON(json: any): ModelBoolean {
    return ModelBooleanToJSONTyped(json, false);
}

export function ModelBooleanToJSONTyped(value?: ModelBoolean | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'boolean': FreelanceJobsDetailParameterbooleanToJSON(value['_boolean']),
    };
}

