/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Error 520
 * @export
 * @interface PostCharactersCharacterIdMailError520
 */
export interface PostCharactersCharacterIdMailError520 {
    /**
     * Error 520 message
     * @type {string}
     * @memberof PostCharactersCharacterIdMailError520
     */
    error?: string;
}

/**
 * Check if a given object implements the PostCharactersCharacterIdMailError520 interface.
 */
export function instanceOfPostCharactersCharacterIdMailError520(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PostCharactersCharacterIdMailError520FromJSON(json: any): PostCharactersCharacterIdMailError520 {
    return PostCharactersCharacterIdMailError520FromJSONTyped(json, false);
}

export function PostCharactersCharacterIdMailError520FromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCharactersCharacterIdMailError520 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : json['error'],
    };
}

export function PostCharactersCharacterIdMailError520ToJSON(value?: PostCharactersCharacterIdMailError520 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': value.error,
    };
}

