/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostCharactersCharacterIdFittingsRequestItemsInner } from './PostCharactersCharacterIdFittingsRequestItemsInner';
import {
    PostCharactersCharacterIdFittingsRequestItemsInnerFromJSON,
    PostCharactersCharacterIdFittingsRequestItemsInnerFromJSONTyped,
    PostCharactersCharacterIdFittingsRequestItemsInnerToJSON,
    PostCharactersCharacterIdFittingsRequestItemsInnerToJSONTyped,
} from './PostCharactersCharacterIdFittingsRequestItemsInner';

/**
 * 
 * @export
 * @interface PostCharactersCharacterIdFittingsRequest
 */
export interface PostCharactersCharacterIdFittingsRequest {
    /**
     * 
     * @type {string}
     * @memberof PostCharactersCharacterIdFittingsRequest
     */
    description: string;
    /**
     * 
     * @type {Array<PostCharactersCharacterIdFittingsRequestItemsInner>}
     * @memberof PostCharactersCharacterIdFittingsRequest
     */
    items: Array<PostCharactersCharacterIdFittingsRequestItemsInner>;
    /**
     * 
     * @type {string}
     * @memberof PostCharactersCharacterIdFittingsRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof PostCharactersCharacterIdFittingsRequest
     */
    shipTypeId: number;
}

/**
 * Check if a given object implements the PostCharactersCharacterIdFittingsRequest interface.
 */
export function instanceOfPostCharactersCharacterIdFittingsRequest(value: object): value is PostCharactersCharacterIdFittingsRequest {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('shipTypeId' in value) || value['shipTypeId'] === undefined) return false;
    return true;
}

export function PostCharactersCharacterIdFittingsRequestFromJSON(json: any): PostCharactersCharacterIdFittingsRequest {
    return PostCharactersCharacterIdFittingsRequestFromJSONTyped(json, false);
}

export function PostCharactersCharacterIdFittingsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCharactersCharacterIdFittingsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'items': ((json['items'] as Array<any>).map(PostCharactersCharacterIdFittingsRequestItemsInnerFromJSON)),
        'name': json['name'],
        'shipTypeId': json['ship_type_id'],
    };
}

export function PostCharactersCharacterIdFittingsRequestToJSON(json: any): PostCharactersCharacterIdFittingsRequest {
    return PostCharactersCharacterIdFittingsRequestToJSONTyped(json, false);
}

export function PostCharactersCharacterIdFittingsRequestToJSONTyped(value?: PostCharactersCharacterIdFittingsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'items': ((value['items'] as Array<any>).map(PostCharactersCharacterIdFittingsRequestItemsInnerToJSON)),
        'name': value['name'],
        'ship_type_id': value['shipTypeId'],
    };
}

