/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.36
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 200 ok object
 * @export
 * @interface PostCharactersCharacterIdAssetsNames200Ok
 */
export interface PostCharactersCharacterIdAssetsNames200Ok {
    /**
     * item_id integer
     * @type {number}
     * @memberof PostCharactersCharacterIdAssetsNames200Ok
     */
    itemId: number;
    /**
     * name string
     * @type {string}
     * @memberof PostCharactersCharacterIdAssetsNames200Ok
     */
    name: string;
}

/**
 * Check if a given object implements the PostCharactersCharacterIdAssetsNames200Ok interface.
 */
export function instanceOfPostCharactersCharacterIdAssetsNames200Ok(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "itemId" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function PostCharactersCharacterIdAssetsNames200OkFromJSON(json: any): PostCharactersCharacterIdAssetsNames200Ok {
    return PostCharactersCharacterIdAssetsNames200OkFromJSONTyped(json, false);
}

export function PostCharactersCharacterIdAssetsNames200OkFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCharactersCharacterIdAssetsNames200Ok {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'itemId': json['item_id'],
        'name': json['name'],
    };
}

export function PostCharactersCharacterIdAssetsNames200OkToJSON(value?: PostCharactersCharacterIdAssetsNames200Ok | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'item_id': value.itemId,
        'name': value.name,
    };
}

