/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Not found
 * @export
 * @interface PutFleetsFleetIdSquadsSquadIdNotFound
 */
export interface PutFleetsFleetIdSquadsSquadIdNotFound {
    /**
     * Not found message
     * @type {string}
     * @memberof PutFleetsFleetIdSquadsSquadIdNotFound
     */
    error?: string;
}

/**
 * Check if a given object implements the PutFleetsFleetIdSquadsSquadIdNotFound interface.
 */
export function instanceOfPutFleetsFleetIdSquadsSquadIdNotFound(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PutFleetsFleetIdSquadsSquadIdNotFoundFromJSON(json: any): PutFleetsFleetIdSquadsSquadIdNotFound {
    return PutFleetsFleetIdSquadsSquadIdNotFoundFromJSONTyped(json, false);
}

export function PutFleetsFleetIdSquadsSquadIdNotFoundFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutFleetsFleetIdSquadsSquadIdNotFound {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : json['error'],
    };
}

export function PutFleetsFleetIdSquadsSquadIdNotFoundToJSON(value?: PutFleetsFleetIdSquadsSquadIdNotFound | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': value.error,
    };
}

