/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StructureId
 */
export interface StructureId {
    /**
     * 
     * @type {number}
     * @memberof StructureId
     */
    structureId?: number;
}

/**
 * Check if a given object implements the StructureId interface.
 */
export function instanceOfStructureId(value: object): value is StructureId {
    return true;
}

export function StructureIdFromJSON(json: any): StructureId {
    return StructureIdFromJSONTyped(json, false);
}

export function StructureIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): StructureId {
    if (json == null) {
        return json;
    }
    return {
        
        'structureId': json['structure_id'] == null ? undefined : json['structure_id'],
    };
}

export function StructureIdToJSON(json: any): StructureId {
    return StructureIdToJSONTyped(json, false);
}

export function StructureIdToJSONTyped(value?: StructureId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'structure_id': value['structureId'],
    };
}

