/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CharactersCharacterIdAssetsLocationsPostInnerPosition } from './CharactersCharacterIdAssetsLocationsPostInnerPosition';
import {
    CharactersCharacterIdAssetsLocationsPostInnerPositionFromJSON,
    CharactersCharacterIdAssetsLocationsPostInnerPositionFromJSONTyped,
    CharactersCharacterIdAssetsLocationsPostInnerPositionToJSON,
    CharactersCharacterIdAssetsLocationsPostInnerPositionToJSONTyped,
} from './CharactersCharacterIdAssetsLocationsPostInnerPosition';

/**
 * 
 * @export
 * @interface UniverseAsteroidBeltsAsteroidBeltIdGet
 */
export interface UniverseAsteroidBeltsAsteroidBeltIdGet {
    /**
     * 
     * @type {string}
     * @memberof UniverseAsteroidBeltsAsteroidBeltIdGet
     */
    name: string;
    /**
     * 
     * @type {CharactersCharacterIdAssetsLocationsPostInnerPosition}
     * @memberof UniverseAsteroidBeltsAsteroidBeltIdGet
     */
    position: CharactersCharacterIdAssetsLocationsPostInnerPosition;
    /**
     * The solar system this asteroid belt is in
     * @type {number}
     * @memberof UniverseAsteroidBeltsAsteroidBeltIdGet
     */
    systemId: number;
}

/**
 * Check if a given object implements the UniverseAsteroidBeltsAsteroidBeltIdGet interface.
 */
export function instanceOfUniverseAsteroidBeltsAsteroidBeltIdGet(value: object): value is UniverseAsteroidBeltsAsteroidBeltIdGet {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('position' in value) || value['position'] === undefined) return false;
    if (!('systemId' in value) || value['systemId'] === undefined) return false;
    return true;
}

export function UniverseAsteroidBeltsAsteroidBeltIdGetFromJSON(json: any): UniverseAsteroidBeltsAsteroidBeltIdGet {
    return UniverseAsteroidBeltsAsteroidBeltIdGetFromJSONTyped(json, false);
}

export function UniverseAsteroidBeltsAsteroidBeltIdGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): UniverseAsteroidBeltsAsteroidBeltIdGet {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'position': CharactersCharacterIdAssetsLocationsPostInnerPositionFromJSON(json['position']),
        'systemId': json['system_id'],
    };
}

export function UniverseAsteroidBeltsAsteroidBeltIdGetToJSON(json: any): UniverseAsteroidBeltsAsteroidBeltIdGet {
    return UniverseAsteroidBeltsAsteroidBeltIdGetToJSONTyped(json, false);
}

export function UniverseAsteroidBeltsAsteroidBeltIdGetToJSONTyped(value?: UniverseAsteroidBeltsAsteroidBeltIdGet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'position': CharactersCharacterIdAssetsLocationsPostInnerPositionToJSON(value['position']),
        'system_id': value['systemId'],
    };
}

