/* tslint:disable */
/* eslint-disable */
/**
 * EVE Ref Reference Data for EVE Online
 * This spec should be considered unstable and subject to change at any time.
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Coordinate2D
 */
export interface Coordinate2D {
    /**
     * 
     * @type {number}
     * @memberof Coordinate2D
     */
    x?: number;
    /**
     * 
     * @type {number}
     * @memberof Coordinate2D
     */
    y?: number;
}

/**
 * Check if a given object implements the Coordinate2D interface.
 */
export function instanceOfCoordinate2D(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Coordinate2DFromJSON(json: any): Coordinate2D {
    return Coordinate2DFromJSONTyped(json, false);
}

export function Coordinate2DFromJSONTyped(json: any, ignoreDiscriminator: boolean): Coordinate2D {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'x': !exists(json, 'x') ? undefined : json['x'],
        'y': !exists(json, 'y') ? undefined : json['y'],
    };
}

export function Coordinate2DToJSON(value?: Coordinate2D | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'x': value.x,
        'y': value.y,
    };
}

