/* tslint:disable */
/* eslint-disable */
/**
 * EVE Ref Reference Data for EVE Online
 * This spec should be considered unstable and subject to change at any time.
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A specific value for a dogma effect.
 * @export
 * @interface DogmaTypeEffect
 */
export interface DogmaTypeEffect {
    /**
     * 
     * @type {number}
     * @memberof DogmaTypeEffect
     */
    effectId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof DogmaTypeEffect
     */
    isDefault?: boolean;
}

/**
 * Check if a given object implements the DogmaTypeEffect interface.
 */
export function instanceOfDogmaTypeEffect(value: object): value is DogmaTypeEffect {
    return true;
}

export function DogmaTypeEffectFromJSON(json: any): DogmaTypeEffect {
    return DogmaTypeEffectFromJSONTyped(json, false);
}

export function DogmaTypeEffectFromJSONTyped(json: any, ignoreDiscriminator: boolean): DogmaTypeEffect {
    if (json == null) {
        return json;
    }
    return {
        
        'effectId': json['effect_id'] == null ? undefined : json['effect_id'],
        'isDefault': json['is_default'] == null ? undefined : json['is_default'],
    };
}

export function DogmaTypeEffectToJSON(json: any): DogmaTypeEffect {
    return DogmaTypeEffectToJSONTyped(json, false);
}

export function DogmaTypeEffectToJSONTyped(value?: DogmaTypeEffect | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'effect_id': value['effectId'],
        'is_default': value['isDefault'],
    };
}

