/* tslint:disable */
/* eslint-disable */
/**
 * EVE Ref Reference Data for EVE Online
 * This spec should be considered unstable and subject to change at any time.
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Details about how much a dogma attribute can be modified by a mutaplasmid. These are created by EVE Ref and derived from Hoboleaks.
 * @export
 * @interface MutaplasmidDogmaModifications
 */
export interface MutaplasmidDogmaModifications {
    /**
     * 
     * @type {number}
     * @memberof MutaplasmidDogmaModifications
     */
    min?: number;
    /**
     * 
     * @type {number}
     * @memberof MutaplasmidDogmaModifications
     */
    max?: number;
    /**
     * 
     * @type {boolean}
     * @memberof MutaplasmidDogmaModifications
     */
    highIsGood?: boolean;
}

/**
 * Check if a given object implements the MutaplasmidDogmaModifications interface.
 */
export function instanceOfMutaplasmidDogmaModifications(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MutaplasmidDogmaModificationsFromJSON(json: any): MutaplasmidDogmaModifications {
    return MutaplasmidDogmaModificationsFromJSONTyped(json, false);
}

export function MutaplasmidDogmaModificationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MutaplasmidDogmaModifications {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'min': !exists(json, 'min') ? undefined : json['min'],
        'max': !exists(json, 'max') ? undefined : json['max'],
        'highIsGood': !exists(json, 'high_is_good') ? undefined : json['high_is_good'],
    };
}

export function MutaplasmidDogmaModificationsToJSON(value?: MutaplasmidDogmaModifications | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'min': value.min,
        'max': value.max,
        'high_is_good': value.highIsGood,
    };
}

