/* tslint:disable */
/* eslint-disable */
/**
 * EVE Ref Reference Data for EVE Online
 * This spec should be considered unstable and subject to change at any time.
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefDataMetaFileInfo
 */
export interface RefDataMetaFileInfo {
    /**
     * 
     * @type {string}
     * @memberof RefDataMetaFileInfo
     */
    sha256?: string;
}

/**
 * Check if a given object implements the RefDataMetaFileInfo interface.
 */
export function instanceOfRefDataMetaFileInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RefDataMetaFileInfoFromJSON(json: any): RefDataMetaFileInfo {
    return RefDataMetaFileInfoFromJSONTyped(json, false);
}

export function RefDataMetaFileInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefDataMetaFileInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sha256': !exists(json, 'sha256') ? undefined : json['sha256'],
    };
}

export function RefDataMetaFileInfoToJSON(value?: RefDataMetaFileInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sha256': value.sha256,
    };
}

