openapi: 3.0.1
info:
  description: This spec should be considered unstable and subject to change at any
    time.
  license:
    name: MIT-0
    url: https://github.com/autonomouslogic/eve-ref/blob/main/LICENSE
  title: EVE Ref API
  version: dev
servers:
- url: https://api.everef.net
paths:
  /v1/industry/cost:
    get:
      operationId: industryCost
      parameters:
      - explode: true
        in: query
        name: input
        schema:
          $ref: "#/components/schemas/IndustryCostInput"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IndustryCost"
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
          description: Client error
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
          description: Server error
      tags:
      - industry
components:
  schemas:
    ActivityCost:
      type: object
      properties:
        estimated_item_value:
          type: number
        facility_tax:
          type: number
        materials:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/MaterialCost"
        product_type_id:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
        scc_surcharge:
          type: number
        system_cost_index:
          type: number
        time:
          type: string
    ApiError:
      type: object
      properties:
        message:
          type: string
    IndustryCost:
      type: object
      properties:
        input:
          $ref: "#/components/schemas/IndustryCostInput"
        manufacturing:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/ActivityCost"
    IndustryCostInput:
      type: object
      properties:
        advanced_industry:
          type: integer
          format: int32
          default: 5
          description: The Advanced Industry skill level the installing character
          maximum: 5
          minimum: 0
        alpha:
          type: boolean
          default: false
          description: Whether installing character is an alpha clone or not
        copying_cost:
          type: number
          default: 0
          description: The copying cost index of the system where the job is installed
          maximum: 1
          minimum: 0
        datacore1:
          type: integer
          format: int32
          default: 5
          description: The level of one of the datacore related skills the installing
            character
          maximum: 5
          minimum: 0
        datacore2:
          type: integer
          format: int32
          default: 5
          description: The level of the other of the datacore related skills the installing
            character
          maximum: 5
          minimum: 0
        decryption:
          type: integer
          format: int32
          default: 5
          description: The level of relevant encryption skills the installing character
          maximum: 5
          minimum: 0
        facility_tax:
          type: number
          default: 0
          description: The facility tax rate of the station or structure where the
            job is installed
          maximum: 1
          minimum: 0
        industry:
          type: integer
          format: int32
          default: 5
          description: The Industry skill level the installing character
          maximum: 5
          minimum: 0
        invention_cost:
          type: number
          default: 0
          description: The invention cost index of the system where the job is installed
          maximum: 1
          minimum: 0
        manufacturing_cost:
          type: number
          default: 0
          description: The manufacturing cost index of the system where the job is
            installed
          maximum: 1
          minimum: 0
        me:
          type: integer
          format: int32
          default: 10
          description: The material efficiency of the blueprint
          maximum: 10
          minimum: 0
        metallurgy:
          type: integer
          format: int32
          default: 5
          description: The Metallurgy skill level the installing character
          maximum: 5
          minimum: 0
        product_id:
          type: integer
          format: int64
          description: The desired product type ID
          minimum: 1
        reaction_cost:
          type: number
          default: 0
          description: The reaction cost index of the system where the job is installed
          maximum: 1
          minimum: 0
        research:
          type: integer
          format: int32
          default: 5
          description: The Research skill level the installing character
          maximum: 5
          minimum: 0
        researching_me_cost:
          type: number
          default: 0
          description: The researching material efficiency cost index of the system
            where the job is installed
          maximum: 1
          minimum: 0
        researching_te_cost:
          type: number
          default: 0
          description: The researching time efficiency cost index of the system where
            the job is installed
          maximum: 1
          minimum: 0
        runs:
          type: integer
          format: int32
          default: 1
          description: The number of runs
          minimum: 1
        scc:
          type: number
          default: 0.04
          description: The SCC surcharge rate
          maximum: 1
          minimum: 0
        science:
          type: integer
          format: int32
          default: 5
          description: The Science skill level the installing character
          maximum: 5
          minimum: 0
        security:
          type: string
          default: HIGH_SEC
          description: The security class of the system where the job is installed
          enum:
          - HIGH_SEC
          - LOW_SEC
          - NULL_SEC
          - WORMHOLE
        structure_class:
          type: string
          default: STATION
          description: The type of station or structure where the job is installed
          enum:
          - STATION
          - ENGINEERING_COMPLEX
        structure_size:
          type: string
          description: The size of structure where the job is installed
          enum:
          - MEDIUM
          - LARGE
          - XLARGE
        te:
          type: integer
          format: int32
          default: 20
          description: The time efficiency of the blueprint
          maximum: 20
          minimum: 0
      required:
      - product_id
    MaterialCost:
      type: object
      properties:
        cost:
          type: number
        quantity:
          type: integer
          format: int64
        type_id:
          type: integer
          format: int64
