openapi: 3.0.1
info:
  description: This spec should be considered unstable and subject to change at any
    time.
  license:
    name: MIT-0
    url: https://github.com/autonomouslogic/eve-ref/blob/main/LICENSE
  title: EVE Ref API
  version: dev
servers:
- url: https://api.everef.net
paths:
  /v1/industry/cost:
    get:
      operationId: industryCost
      parameters:
      - explode: true
        in: query
        name: input
        schema:
          $ref: "#/components/schemas/IndustryCostInput"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IndustryCost"
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
          description: Client error
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
          description: Server error
      tags:
      - industry
components:
  schemas:
    ActivityCost:
      type: object
      properties:
        estimated_item_value:
          type: number
        facility_tax:
          type: number
        materials:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/MaterialCost"
        product_type_id:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
        scc_surcharge:
          type: number
        system_cost_index:
          type: number
        time:
          type: string
    ApiError:
      type: object
      properties:
        message:
          type: string
    IndustryCost:
      type: object
      properties:
        copying:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/ActivityCost"
        input:
          $ref: "#/components/schemas/IndustryCostInput"
        invention:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/InventionCost"
        manufacturing:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/ActivityCost"
        me_research:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/ActivityCost"
        te_research:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/ActivityCost"
    IndustryCostInput:
      type: object
      properties:
        advanced_industry_level:
          type: integer
          format: int32
        copying_cost_index:
          type: number
        copying_rig_tech_level:
          type: string
          enum:
          - T1
          - T2
        datacore1_level:
          type: integer
          format: int32
        datacore2_level:
          type: integer
          format: int32
        decryption_level:
          type: integer
          format: int32
        decryptor_type_id:
          type: integer
          format: int64
        facility_tax_rate:
          type: number
        industry_level:
          type: integer
          format: int32
        invention_cost_index:
          type: number
        invention_rig_tech_level:
          type: string
          enum:
          - T1
          - T2
        manufacturing_cost_index:
          type: number
        material_efficiency:
          type: integer
          format: int32
        material_efficiency_rig_tech_level:
          type: string
          enum:
          - T1
          - T2
        metallurgy_level:
          type: integer
          format: int32
        product_type_ids:
          type: array
          items:
            type: integer
            format: int64
          uniqueItems: true
        reaction_cost_index:
          type: number
        research_level:
          type: integer
          format: int32
        researching_material_efficiency_cost_index:
          type: number
        researching_time_efficiency_cost_index:
          type: number
        runs:
          type: integer
          format: int32
        scc_surcharge_rate:
          type: number
        science_level:
          type: integer
          format: int32
        security_class:
          type: string
          enum:
          - HIGH_SEC
          - LOW_SEC
          - NULL_SEC
          - WORMHOLE
        structure_type_id:
          type: integer
          format: int64
        time_efficiency:
          type: integer
          format: int32
        time_efficiency_rig_tech_level:
          type: string
          enum:
          - T1
          - T2
    InventionCost:
      type: object
      properties:
        estimated_item_value:
          type: number
        facility_tax:
          type: number
        job_cost_base:
          type: number
        material_efficiency:
          type: integer
          format: int32
        materials:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/MaterialCost"
        probability:
          type: number
        product_type_id:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
        runs:
          type: integer
          format: int32
        scc_surcharge:
          type: number
        system_cost_index:
          type: number
        time:
          type: string
        time_efficiency:
          type: integer
          format: int32
    MaterialCost:
      type: object
      properties:
        cost:
          type: number
        quantity:
          type: integer
          format: int64
        type_id:
          type: integer
          format: int64
