openapi: 3.0.1
info:
  title: EVE Ref Reference Data for EVE Online
  description: This spec should be considered unstable and subject to change at any
    time.
  license:
    name: CCP
    url: https://github.com/autonomouslogic/eve-ref/blob/main/LICENSE-CCP
  version: dev
externalDocs:
  description: Reference data
  url: https://github.com/autonomouslogic/eve-ref/blob/main/docs/refdata.md
servers:
- url: https://ref-data.everef.net
  variables: {}
paths:
  /types:
    get:
      tags:
      - refdata
      description: Get all type IDs.
      operationId: getAllTypes
      responses:
        "200":
          description: Type IDs.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
                  format: int32
  /types/{type_id}:
    get:
      tags:
      - refdata
      operationId: getType
      parameters:
      - name: type_id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: Types.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InventoryType'
components:
  schemas:
    DogmaTypeAttribute:
      type: object
      properties:
        attribute_id:
          type: integer
          format: int32
        value:
          type: number
          format: double
      description: A specific value for a dogma attribute
    DogmaTypeEffect:
      type: object
      properties:
        effect_id:
          type: integer
          format: int32
        is_default:
          type: boolean
        default:
          type: boolean
      description: A specific value for a dogma effect.
    InventoryType:
      type: object
      properties:
        base_price:
          type: number
        capacity:
          type: number
          format: double
        description:
          type: object
          additionalProperties:
            type: string
            description: The key is the language code.
          description: The key is the language code.
        dogma_attributes:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/DogmaTypeAttribute'
          description: A map of dogma attributes. The key is the attribute ID
        dogma_effects:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/DogmaTypeEffect'
          description: A map of dogma attributes. The key is the attribute ID
        faction_id:
          type: integer
          format: int32
        graphic_id:
          type: integer
          format: int32
        group_id:
          type: integer
          format: int32
        icon_id:
          type: integer
          format: int32
        market_group_id:
          type: integer
          format: int32
        mass:
          type: number
        masteries:
          type: object
          additionalProperties:
            type: array
            items:
              type: integer
              format: int32
        meta_group_id:
          type: integer
          format: int32
        name:
          type: object
          additionalProperties:
            type: string
            description: The key is the language code.
          description: The key is the language code.
        packaged_volume:
          type: number
          format: double
        portion_size:
          type: integer
          format: int32
        published:
          type: boolean
        race_id:
          type: integer
          format: int32
        radius:
          type: number
          format: double
        sof_faction_name:
          type: string
        sof_material_set_id:
          type: integer
          format: int32
        sound_id:
          type: integer
          format: int32
        traits:
          $ref: '#/components/schemas/InventoryTypeTraits'
        type_id:
          type: integer
          format: int32
        variation_parent_type_id:
          type: integer
          format: int32
        volume:
          type: number
      description: An inventory type
    InventoryTypeTraits:
      type: object
      properties:
        misc_bonuses:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/TraitBonus'
        role_bonuses:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/TraitBonus'
        types:
          type: object
          additionalProperties:
            type: object
            additionalProperties:
              $ref: '#/components/schemas/TraitBonus'
        icon_id:
          type: integer
          format: int32
    TraitBonus:
      type: object
      properties:
        bonus:
          type: number
          format: double
        bonus_text:
          type: object
          additionalProperties:
            type: string
            description: The key is the language code.
          description: The key is the language code.
        importance:
          type: integer
          format: int32
        is_positive:
          type: boolean
        unit_id:
          type: integer
          format: int32
