export const PLEX_TYPE_ID = 44992;
export const MULTIPLE_PILOT_TRAINING_CERTIFICATE = 34133;
export const DAILY_ALPHA_INJECTOR = 46375;
export const SMALL_SKILL_INJECTOR = 45635;
export const LARGE_SKILL_INJECTOR = 40520;

export const MASTER_AT_ARMS_CEREBRAL_ACCELERATOR = 48582;
export const PROTOTYPE_CEREBRAL_ACCELERATOR = 33111;
export const BASIC_BOOST_CEREBRAL_ACCELERATOR = 72238;
export const STANDARD_BOOST_CEREBRAL_ACCELERATOR = 72239;
export const ADVANCED_BOOST_CEREBRAL_ACCELERATOR = 72240;
export const SPECIALIST_BOOST_CEREBRAL_ACCELERATOR = 72241;
export const EXPERT_BOOST_CEREBRAL_ACCELERATOR = 72242;
export const GENIUS_BOOST_CEREBRAL_ACCELERATOR = 77919;
