/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CorporationsProjectsContribution,
  CorporationsProjectsContributors,
  CorporationsProjectsDetail,
  CorporationsProjectsListing,
} from '../models/index';
import {
    CorporationsProjectsContributionFromJSON,
    CorporationsProjectsContributionToJSON,
    CorporationsProjectsContributorsFromJSON,
    CorporationsProjectsContributorsToJSON,
    CorporationsProjectsDetailFromJSON,
    CorporationsProjectsDetailToJSON,
    CorporationsProjectsListingFromJSON,
    CorporationsProjectsListingToJSON,
} from '../models/index';

export interface GetCorporationsProjectsContributionRequest {
    corporationId: number;
    projectId: string;
    characterId: number;
    xCompatibilityDate: GetCorporationsProjectsContributionXCompatibilityDateEnum;
    ifModifiedSince?: string;
    acceptLanguage?: GetCorporationsProjectsContributionAcceptLanguageEnum;
    ifNoneMatch?: string;
    xTenant?: string;
}

export interface GetCorporationsProjectsContributorsRequest {
    corporationId: number;
    projectId: string;
    xCompatibilityDate: GetCorporationsProjectsContributorsXCompatibilityDateEnum;
    after?: string;
    before?: string;
    limit?: number;
    acceptLanguage?: GetCorporationsProjectsContributorsAcceptLanguageEnum;
    ifNoneMatch?: string;
    xTenant?: string;
}

export interface GetCorporationsProjectsDetailRequest {
    corporationId: number;
    projectId: string;
    xCompatibilityDate: GetCorporationsProjectsDetailXCompatibilityDateEnum;
    ifModifiedSince?: string;
    acceptLanguage?: GetCorporationsProjectsDetailAcceptLanguageEnum;
    ifNoneMatch?: string;
    xTenant?: string;
}

export interface GetCorporationsProjectsListingRequest {
    corporationId: number;
    xCompatibilityDate: GetCorporationsProjectsListingXCompatibilityDateEnum;
    after?: string;
    before?: string;
    limit?: number;
    state?: GetCorporationsProjectsListingStateEnum;
    acceptLanguage?: GetCorporationsProjectsListingAcceptLanguageEnum;
    ifNoneMatch?: string;
    xTenant?: string;
}

/**
 * 
 */
export class CorporationProjectsApi extends runtime.BaseAPI {

    /**
     * Show your contribution to a corporation project.
     * Get your project contribution
     */
    async getCorporationsProjectsContributionRaw(requestParameters: GetCorporationsProjectsContributionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CorporationsProjectsContribution>> {
        if (requestParameters['corporationId'] == null) {
            throw new runtime.RequiredError(
                'corporationId',
                'Required parameter "corporationId" was null or undefined when calling getCorporationsProjectsContribution().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getCorporationsProjectsContribution().'
            );
        }

        if (requestParameters['characterId'] == null) {
            throw new runtime.RequiredError(
                'characterId',
                'Required parameter "characterId" was null or undefined when calling getCorporationsProjectsContribution().'
            );
        }

        if (requestParameters['xCompatibilityDate'] == null) {
            throw new runtime.RequiredError(
                'xCompatibilityDate',
                'Required parameter "xCompatibilityDate" was null or undefined when calling getCorporationsProjectsContribution().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['ifModifiedSince'] != null) {
            headerParameters['If-Modified-Since'] = String(requestParameters['ifModifiedSince']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['ifNoneMatch'] != null) {
            headerParameters['If-None-Match'] = String(requestParameters['ifNoneMatch']);
        }

        if (requestParameters['xCompatibilityDate'] != null) {
            headerParameters['X-Compatibility-Date'] = String(requestParameters['xCompatibilityDate']);
        }

        if (requestParameters['xTenant'] != null) {
            headerParameters['X-Tenant'] = String(requestParameters['xTenant']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["esi-corporations.read_projects.v1"]);
        }


        let urlPath = `/corporations/{corporation_id}/projects/{project_id}/contribution/{character_id}`;
        urlPath = urlPath.replace(`{${"corporation_id"}}`, encodeURIComponent(String(requestParameters['corporationId'])));
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"character_id"}}`, encodeURIComponent(String(requestParameters['characterId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CorporationsProjectsContributionFromJSON(jsonValue));
    }

    /**
     * Show your contribution to a corporation project.
     * Get your project contribution
     */
    async getCorporationsProjectsContribution(requestParameters: GetCorporationsProjectsContributionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CorporationsProjectsContribution> {
        const response = await this.getCorporationsProjectsContributionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Listing of all contributors to a corporation project.
     * List project contributors
     */
    async getCorporationsProjectsContributorsRaw(requestParameters: GetCorporationsProjectsContributorsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CorporationsProjectsContributors>> {
        if (requestParameters['corporationId'] == null) {
            throw new runtime.RequiredError(
                'corporationId',
                'Required parameter "corporationId" was null or undefined when calling getCorporationsProjectsContributors().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getCorporationsProjectsContributors().'
            );
        }

        if (requestParameters['xCompatibilityDate'] == null) {
            throw new runtime.RequiredError(
                'xCompatibilityDate',
                'Required parameter "xCompatibilityDate" was null or undefined when calling getCorporationsProjectsContributors().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['after'] != null) {
            queryParameters['after'] = requestParameters['after'];
        }

        if (requestParameters['before'] != null) {
            queryParameters['before'] = requestParameters['before'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['ifNoneMatch'] != null) {
            headerParameters['If-None-Match'] = String(requestParameters['ifNoneMatch']);
        }

        if (requestParameters['xCompatibilityDate'] != null) {
            headerParameters['X-Compatibility-Date'] = String(requestParameters['xCompatibilityDate']);
        }

        if (requestParameters['xTenant'] != null) {
            headerParameters['X-Tenant'] = String(requestParameters['xTenant']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["esi-corporations.read_projects.v1"]);
        }


        let urlPath = `/corporations/{corporation_id}/projects/{project_id}/contributors`;
        urlPath = urlPath.replace(`{${"corporation_id"}}`, encodeURIComponent(String(requestParameters['corporationId'])));
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CorporationsProjectsContributorsFromJSON(jsonValue));
    }

    /**
     * Listing of all contributors to a corporation project.
     * List project contributors
     */
    async getCorporationsProjectsContributors(requestParameters: GetCorporationsProjectsContributorsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CorporationsProjectsContributors> {
        const response = await this.getCorporationsProjectsContributorsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the details of a corporation project.
     * Get project details
     */
    async getCorporationsProjectsDetailRaw(requestParameters: GetCorporationsProjectsDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CorporationsProjectsDetail>> {
        if (requestParameters['corporationId'] == null) {
            throw new runtime.RequiredError(
                'corporationId',
                'Required parameter "corporationId" was null or undefined when calling getCorporationsProjectsDetail().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getCorporationsProjectsDetail().'
            );
        }

        if (requestParameters['xCompatibilityDate'] == null) {
            throw new runtime.RequiredError(
                'xCompatibilityDate',
                'Required parameter "xCompatibilityDate" was null or undefined when calling getCorporationsProjectsDetail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['ifModifiedSince'] != null) {
            headerParameters['If-Modified-Since'] = String(requestParameters['ifModifiedSince']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['ifNoneMatch'] != null) {
            headerParameters['If-None-Match'] = String(requestParameters['ifNoneMatch']);
        }

        if (requestParameters['xCompatibilityDate'] != null) {
            headerParameters['X-Compatibility-Date'] = String(requestParameters['xCompatibilityDate']);
        }

        if (requestParameters['xTenant'] != null) {
            headerParameters['X-Tenant'] = String(requestParameters['xTenant']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["esi-corporations.read_projects.v1"]);
        }


        let urlPath = `/corporations/{corporation_id}/projects/{project_id}`;
        urlPath = urlPath.replace(`{${"corporation_id"}}`, encodeURIComponent(String(requestParameters['corporationId'])));
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CorporationsProjectsDetailFromJSON(jsonValue));
    }

    /**
     * Get the details of a corporation project.
     * Get project details
     */
    async getCorporationsProjectsDetail(requestParameters: GetCorporationsProjectsDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CorporationsProjectsDetail> {
        const response = await this.getCorporationsProjectsDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Listing of all (active) corporation projects.
     * List corporation projects
     */
    async getCorporationsProjectsListingRaw(requestParameters: GetCorporationsProjectsListingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CorporationsProjectsListing>> {
        if (requestParameters['corporationId'] == null) {
            throw new runtime.RequiredError(
                'corporationId',
                'Required parameter "corporationId" was null or undefined when calling getCorporationsProjectsListing().'
            );
        }

        if (requestParameters['xCompatibilityDate'] == null) {
            throw new runtime.RequiredError(
                'xCompatibilityDate',
                'Required parameter "xCompatibilityDate" was null or undefined when calling getCorporationsProjectsListing().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['after'] != null) {
            queryParameters['after'] = requestParameters['after'];
        }

        if (requestParameters['before'] != null) {
            queryParameters['before'] = requestParameters['before'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['state'] != null) {
            queryParameters['state'] = requestParameters['state'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['ifNoneMatch'] != null) {
            headerParameters['If-None-Match'] = String(requestParameters['ifNoneMatch']);
        }

        if (requestParameters['xCompatibilityDate'] != null) {
            headerParameters['X-Compatibility-Date'] = String(requestParameters['xCompatibilityDate']);
        }

        if (requestParameters['xTenant'] != null) {
            headerParameters['X-Tenant'] = String(requestParameters['xTenant']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["esi-corporations.read_projects.v1"]);
        }


        let urlPath = `/corporations/{corporation_id}/projects`;
        urlPath = urlPath.replace(`{${"corporation_id"}}`, encodeURIComponent(String(requestParameters['corporationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CorporationsProjectsListingFromJSON(jsonValue));
    }

    /**
     * Listing of all (active) corporation projects.
     * List corporation projects
     */
    async getCorporationsProjectsListing(requestParameters: GetCorporationsProjectsListingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CorporationsProjectsListing> {
        const response = await this.getCorporationsProjectsListingRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetCorporationsProjectsContributionXCompatibilityDateEnum = {
    _20251216: '2025-12-16'
} as const;
export type GetCorporationsProjectsContributionXCompatibilityDateEnum = typeof GetCorporationsProjectsContributionXCompatibilityDateEnum[keyof typeof GetCorporationsProjectsContributionXCompatibilityDateEnum];
/**
 * @export
 */
export const GetCorporationsProjectsContributionAcceptLanguageEnum = {
    En: 'en',
    De: 'de',
    Fr: 'fr',
    Ja: 'ja',
    Ru: 'ru',
    Zh: 'zh',
    Ko: 'ko',
    Es: 'es'
} as const;
export type GetCorporationsProjectsContributionAcceptLanguageEnum = typeof GetCorporationsProjectsContributionAcceptLanguageEnum[keyof typeof GetCorporationsProjectsContributionAcceptLanguageEnum];
/**
 * @export
 */
export const GetCorporationsProjectsContributorsXCompatibilityDateEnum = {
    _20251216: '2025-12-16'
} as const;
export type GetCorporationsProjectsContributorsXCompatibilityDateEnum = typeof GetCorporationsProjectsContributorsXCompatibilityDateEnum[keyof typeof GetCorporationsProjectsContributorsXCompatibilityDateEnum];
/**
 * @export
 */
export const GetCorporationsProjectsContributorsAcceptLanguageEnum = {
    En: 'en',
    De: 'de',
    Fr: 'fr',
    Ja: 'ja',
    Ru: 'ru',
    Zh: 'zh',
    Ko: 'ko',
    Es: 'es'
} as const;
export type GetCorporationsProjectsContributorsAcceptLanguageEnum = typeof GetCorporationsProjectsContributorsAcceptLanguageEnum[keyof typeof GetCorporationsProjectsContributorsAcceptLanguageEnum];
/**
 * @export
 */
export const GetCorporationsProjectsDetailXCompatibilityDateEnum = {
    _20251216: '2025-12-16'
} as const;
export type GetCorporationsProjectsDetailXCompatibilityDateEnum = typeof GetCorporationsProjectsDetailXCompatibilityDateEnum[keyof typeof GetCorporationsProjectsDetailXCompatibilityDateEnum];
/**
 * @export
 */
export const GetCorporationsProjectsDetailAcceptLanguageEnum = {
    En: 'en',
    De: 'de',
    Fr: 'fr',
    Ja: 'ja',
    Ru: 'ru',
    Zh: 'zh',
    Ko: 'ko',
    Es: 'es'
} as const;
export type GetCorporationsProjectsDetailAcceptLanguageEnum = typeof GetCorporationsProjectsDetailAcceptLanguageEnum[keyof typeof GetCorporationsProjectsDetailAcceptLanguageEnum];
/**
 * @export
 */
export const GetCorporationsProjectsListingXCompatibilityDateEnum = {
    _20251216: '2025-12-16'
} as const;
export type GetCorporationsProjectsListingXCompatibilityDateEnum = typeof GetCorporationsProjectsListingXCompatibilityDateEnum[keyof typeof GetCorporationsProjectsListingXCompatibilityDateEnum];
/**
 * @export
 */
export const GetCorporationsProjectsListingStateEnum = {
    All: 'All',
    Active: 'Active'
} as const;
export type GetCorporationsProjectsListingStateEnum = typeof GetCorporationsProjectsListingStateEnum[keyof typeof GetCorporationsProjectsListingStateEnum];
/**
 * @export
 */
export const GetCorporationsProjectsListingAcceptLanguageEnum = {
    En: 'en',
    De: 'de',
    Fr: 'fr',
    Ja: 'ja',
    Ru: 'ru',
    Zh: 'zh',
    Ko: 'ko',
    Es: 'es'
} as const;
export type GetCorporationsProjectsListingAcceptLanguageEnum = typeof GetCorporationsProjectsListingAcceptLanguageEnum[keyof typeof GetCorporationsProjectsListingAcceptLanguageEnum];
