/* tslint:disable */
/* eslint-disable */
/**
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-12-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MetaChangelog,
  MetaCompatibilityDates,
  MetaStatus,
} from '../models/index';
import {
    MetaChangelogFromJSON,
    MetaChangelogToJSON,
    MetaCompatibilityDatesFromJSON,
    MetaCompatibilityDatesToJSON,
    MetaStatusFromJSON,
    MetaStatusToJSON,
} from '../models/index';

export interface GetMetaChangelogRequest {
    xCompatibilityDate: GetMetaChangelogXCompatibilityDateEnum;
    acceptLanguage?: GetMetaChangelogAcceptLanguageEnum;
    ifNoneMatch?: string;
    xTenant?: string;
}

export interface GetMetaCompatibilityDatesRequest {
    xCompatibilityDate: GetMetaCompatibilityDatesXCompatibilityDateEnum;
    acceptLanguage?: GetMetaCompatibilityDatesAcceptLanguageEnum;
    ifNoneMatch?: string;
    xTenant?: string;
}

export interface GetMetaStatusRequest {
    xCompatibilityDate: GetMetaStatusXCompatibilityDateEnum;
    acceptLanguage?: GetMetaStatusAcceptLanguageEnum;
    ifNoneMatch?: string;
    xTenant?: string;
}

/**
 * 
 */
export class MetaApi extends runtime.BaseAPI {

    /**
     * Get the changelog of this API.
     * Get changelog
     */
    async getMetaChangelogRaw(requestParameters: GetMetaChangelogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MetaChangelog>> {
        if (requestParameters['xCompatibilityDate'] == null) {
            throw new runtime.RequiredError(
                'xCompatibilityDate',
                'Required parameter "xCompatibilityDate" was null or undefined when calling getMetaChangelog().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['ifNoneMatch'] != null) {
            headerParameters['If-None-Match'] = String(requestParameters['ifNoneMatch']);
        }

        if (requestParameters['xCompatibilityDate'] != null) {
            headerParameters['X-Compatibility-Date'] = String(requestParameters['xCompatibilityDate']);
        }

        if (requestParameters['xTenant'] != null) {
            headerParameters['X-Tenant'] = String(requestParameters['xTenant']);
        }


        let urlPath = `/meta/changelog`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetaChangelogFromJSON(jsonValue));
    }

    /**
     * Get the changelog of this API.
     * Get changelog
     */
    async getMetaChangelog(requestParameters: GetMetaChangelogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetaChangelog> {
        const response = await this.getMetaChangelogRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a list of compatibility dates.
     * Get compatibility dates
     */
    async getMetaCompatibilityDatesRaw(requestParameters: GetMetaCompatibilityDatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MetaCompatibilityDates>> {
        if (requestParameters['xCompatibilityDate'] == null) {
            throw new runtime.RequiredError(
                'xCompatibilityDate',
                'Required parameter "xCompatibilityDate" was null or undefined when calling getMetaCompatibilityDates().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['ifNoneMatch'] != null) {
            headerParameters['If-None-Match'] = String(requestParameters['ifNoneMatch']);
        }

        if (requestParameters['xCompatibilityDate'] != null) {
            headerParameters['X-Compatibility-Date'] = String(requestParameters['xCompatibilityDate']);
        }

        if (requestParameters['xTenant'] != null) {
            headerParameters['X-Tenant'] = String(requestParameters['xTenant']);
        }


        let urlPath = `/meta/compatibility-dates`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetaCompatibilityDatesFromJSON(jsonValue));
    }

    /**
     * Get a list of compatibility dates.
     * Get compatibility dates
     */
    async getMetaCompatibilityDates(requestParameters: GetMetaCompatibilityDatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetaCompatibilityDates> {
        const response = await this.getMetaCompatibilityDatesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the health status of each API route.
     * Get health status
     */
    async getMetaStatusRaw(requestParameters: GetMetaStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MetaStatus>> {
        if (requestParameters['xCompatibilityDate'] == null) {
            throw new runtime.RequiredError(
                'xCompatibilityDate',
                'Required parameter "xCompatibilityDate" was null or undefined when calling getMetaStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['ifNoneMatch'] != null) {
            headerParameters['If-None-Match'] = String(requestParameters['ifNoneMatch']);
        }

        if (requestParameters['xCompatibilityDate'] != null) {
            headerParameters['X-Compatibility-Date'] = String(requestParameters['xCompatibilityDate']);
        }

        if (requestParameters['xTenant'] != null) {
            headerParameters['X-Tenant'] = String(requestParameters['xTenant']);
        }


        let urlPath = `/meta/status`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetaStatusFromJSON(jsonValue));
    }

    /**
     * Get the health status of each API route.
     * Get health status
     */
    async getMetaStatus(requestParameters: GetMetaStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetaStatus> {
        const response = await this.getMetaStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetMetaChangelogXCompatibilityDateEnum = {
    _20251216: '2025-12-16'
} as const;
export type GetMetaChangelogXCompatibilityDateEnum = typeof GetMetaChangelogXCompatibilityDateEnum[keyof typeof GetMetaChangelogXCompatibilityDateEnum];
/**
 * @export
 */
export const GetMetaChangelogAcceptLanguageEnum = {
    En: 'en',
    De: 'de',
    Fr: 'fr',
    Ja: 'ja',
    Ru: 'ru',
    Zh: 'zh',
    Ko: 'ko',
    Es: 'es'
} as const;
export type GetMetaChangelogAcceptLanguageEnum = typeof GetMetaChangelogAcceptLanguageEnum[keyof typeof GetMetaChangelogAcceptLanguageEnum];
/**
 * @export
 */
export const GetMetaCompatibilityDatesXCompatibilityDateEnum = {
    _20251216: '2025-12-16'
} as const;
export type GetMetaCompatibilityDatesXCompatibilityDateEnum = typeof GetMetaCompatibilityDatesXCompatibilityDateEnum[keyof typeof GetMetaCompatibilityDatesXCompatibilityDateEnum];
/**
 * @export
 */
export const GetMetaCompatibilityDatesAcceptLanguageEnum = {
    En: 'en',
    De: 'de',
    Fr: 'fr',
    Ja: 'ja',
    Ru: 'ru',
    Zh: 'zh',
    Ko: 'ko',
    Es: 'es'
} as const;
export type GetMetaCompatibilityDatesAcceptLanguageEnum = typeof GetMetaCompatibilityDatesAcceptLanguageEnum[keyof typeof GetMetaCompatibilityDatesAcceptLanguageEnum];
/**
 * @export
 */
export const GetMetaStatusXCompatibilityDateEnum = {
    _20251216: '2025-12-16'
} as const;
export type GetMetaStatusXCompatibilityDateEnum = typeof GetMetaStatusXCompatibilityDateEnum[keyof typeof GetMetaStatusXCompatibilityDateEnum];
/**
 * @export
 */
export const GetMetaStatusAcceptLanguageEnum = {
    En: 'en',
    De: 'de',
    Fr: 'fr',
    Ja: 'ja',
    Ru: 'ru',
    Zh: 'zh',
    Ko: 'ko',
    Es: 'es'
} as const;
export type GetMetaStatusAcceptLanguageEnum = typeof GetMetaStatusAcceptLanguageEnum[keyof typeof GetMetaStatusAcceptLanguageEnum];
