name: "Renovate"

on: [ push ]

jobs:
  Validate:
    name: Validate Renovate config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate
        uses: rinchsan/renovate-config-validator@v0.2.0
